Repository omniosorg/omnios-build, pull requests merged in 2018-11, with the labels that each got.

#1086 curl: update to 7.62.0
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update, security

#1087 curl: update to 7.62.0 (r151028)
  build/curl/build.sh
Labels: backport-PR, package update

#1088 curl: update to 7.62.0 (r151026)
  build/curl/build.sh
Labels: backport-PR, package update

#1089 curl: update to 7.62.0 (r151022)
  build/curl/build.sh
Labels: backport-PR, package update

#1084 Switch to illumos gcc 7.3.0-il-1
  build/gcc7/build.sh
  build/gcc7/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch
  build/gcc7/patches/0004-intl-Don-t-use-UTF-8-quotes.-Ever.patch
  build/gcc7/patches/0005-Implement-fstrict-calling-conventions.patch
  build/gcc7/patches/0006-allow-the-global-disabling-of-function-cloning.patch
  build/gcc7/patches/0007-strict-cc2-check-that-disabling-function-cloning-pre.patch
  build/gcc7/patches/0008-sol2-enable-full-__cxa_atexit-support.patch
  build/gcc7/patches/0010-sol2-Use-appropriate-values-objects-for-the-various-.patch
  build/gcc7/patches/0011-i386-Save-integer-passed-arguments-to-the-stack-to-a.patch
  build/gcc7/patches/0012-16-update-cmn_err-format-specifier.patch
  build/gcc7/patches/0013-19-cmn_err-b-conversion-should-accept-0-flag.patch
  build/gcc7/patches/ld-flags.patch
  build/gcc7/patches/never-omit-frame-pointer.patch
  build/gcc7/patches/no-lrt.patch
  build/gcc7/patches/patch-libgo_runtime_proc.c
  build/gcc7/patches/series
Labels: backport-todo

#1085 Switch to illumos gcc 7.3.0-il-1 (r151028)
  build/gcc7/build.sh
  build/gcc7/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch
  build/gcc7/patches/0004-intl-Don-t-use-UTF-8-quotes.-Ever.patch
  build/gcc7/patches/0005-Implement-fstrict-calling-conventions.patch
  build/gcc7/patches/0006-allow-the-global-disabling-of-function-cloning.patch
  build/gcc7/patches/0007-strict-cc2-check-that-disabling-function-cloning-pre.patch
  build/gcc7/patches/0008-sol2-enable-full-__cxa_atexit-support.patch
  build/gcc7/patches/0010-sol2-Use-appropriate-values-objects-for-the-various-.patch
  build/gcc7/patches/0011-i386-Save-integer-passed-arguments-to-the-stack-to-a.patch
  build/gcc7/patches/0012-16-update-cmn_err-format-specifier.patch
  build/gcc7/patches/0013-19-cmn_err-b-conversion-should-accept-0-flag.patch
  build/gcc7/patches/ld-flags.patch
  build/gcc7/patches/never-omit-frame-pointer.patch
  build/gcc7/patches/no-lrt.patch
  build/gcc7/patches/patch-libgo_runtime_proc.c
  build/gcc7/patches/series
Labels: backport-PR

#1103 package updates
  build/bison/build.sh
  build/bison/patches/fix_gnulib_make_variables.patch
  build/bison/patches/series
  build/bison/testsuite.log
  build/entire/entire.pkg
  build/fio/build.sh
  build/jeos/omnios-userland.pkg
  build/mercurial/build.sh
  build/mozilla-nss-nspr/build.sh
  build/open-vm-tools/build.sh
  build/open-vm-tools/patches/gnu-ld.patch
  build/open-vm-tools/patches/lock.patch
  build/open-vm-tools/patches/nicInfo.patch
  build/open-vm-tools/patches/ucontext.patch
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0014-GSS-API-key-exchange-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/openssl11.patch
  build/openssh/patches/series
  build/sigcpp/build.sh
  build/sigcpp/testsuite.log
  build/sqlite3/build.sh
  build/tmux/build.sh
  doc/packages.md
Labels: package update

#1105 nasm: update to 2.14, move to gcc8
  build/nasm/build.sh
  doc/packages.md
Labels: package update

#1114 openjdk: update to 1.7.0_201-b00
  build/openjdk/build.sh
  doc/packages.md
Labels: backport-todo, package update, security

#1115 openjdk: update to 1.7.0_201-b00 (r22)
  build/openjdk/build.sh
Labels: backport-PR

#1116 openjdk: update to 1.7.0_201-b00 (r26)
  build/openjdk/build.sh
Labels: backport-PR

#1117 openjdk: update to 1.7.0_201-b00 (r28)
  build/openjdk/build.sh
Labels: backport-PR

#1130 openssl: update to 1.1.0i/1.0.2p
  build/openssl/build.sh
  build/openssl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#1131 openssl: update to 1.1.0i/1.0.2p (r151028)
  build/openssl/build.sh
Labels: backport-PR, package update

#1134 openssl: update to 1.1.0i/1.0.2p (r151026)
  build/openssl/build.sh
Labels: backport-PR, package update

#1136 openssl: update to 1.0.2q (r22)
  build/openssl/build.sh
  build/openssl/engine_pkcs11/README.pkcs11
  build/openssl/engine_pkcs11/cryptoki.h
  build/openssl/engine_pkcs11/hw_pk11.c
  build/openssl/engine_pkcs11/hw_pk11_err.c
  build/openssl/engine_pkcs11/hw_pk11_err.h
  build/openssl/engine_pkcs11/hw_pk11_pub.c
  build/openssl/engine_pkcs11/pkcs11.h
  build/openssl/engine_pkcs11/pkcs11f.h
  build/openssl/engine_pkcs11/pkcs11t.h
  build/openssl/local.mog
  build/openssl/patches/pkcs11.patch
  build/openssl/testsuite.log
Labels: backport-PR, package update

#1138 git: update to 2.19.2
  build/git/build.sh
  build/git/testsuite.log
  doc/packages.md
Labels: package update

#1141 Package updates (nghttp2 & bison)
  build/bison/build.sh
  build/bison/testsuite.log
  build/nghttp2/build.sh
  doc/packages.md
Labels: package update

#1139 git: update to 2.19.2 (r151028)
  build/git/build.sh
Labels: backport-PR, package update

#1142 Python module updates.
  build/jeos/omnios-userland.pkg
  build/python35/coverage/build.sh
  build/python35/cryptography/build.sh
  build/python35/setuptools/build.sh
  doc/packages.md
Labels: package update
