Repository omniosorg/omnios-build, pull requests merged in 2018-08, with the labels that each got.

#916 mercurial: update to 4.7
  build/mercurial/build.sh
  doc/packages.md
  lib/config.sh
  lib/functions.sh
Labels: package update

#917 openjdk: update to 1.7.0_191-b01
  build/openjdk/build.sh
  doc/packages.md
Labels: package update

#924 kvm: OS-7090 GDT limit reset to 0xffff
  build/illumos-kvm/build.sh
Labels: backport-PR

#923 kvm: OS-7090 GDT limit reset to 0xffff
  build/illumos-kvm/build.sh
Labels: backport-PR

#919 unixodbc: update to 2.3.7
  build/unixodbc/build.sh
  doc/packages.md
Labels: package update

#918 Python & module updates
  build/python27/cheroot/build.sh
  build/python27/more-itertools/build.sh
  build/python35/build.sh
  build/python35/cheroot/build.sh
  build/python35/more-itertools/build.sh
  build/python35/patches/00-dtrace.patch
  build/python35/patches/01-bits.patch
  build/python35/patches/02-ext-stdio.patch
  build/python35/patches/03-setup.patch
  build/python35/patches/04-vendor-packages.patch
  build/python35/patches/07-ucred.patch
  build/python35/patches/08-dlpi.patch
  build/python35/patches/09-encoding-alias.patch
  build/python35/patches/10-rbac.patch
  build/python35/patches/11-closerange.patch
  build/python35/patches/12-py_db.patch
  build/python35/patches/13-get_wch.patch
  build/python35/patches/14-ossaudiodev.patch
  build/python35/patches/15-include.patch
  build/python35/patches/16-pic-compile.patch
  build/python35/patches/19-SOABI.patch
  build/python35/patches/21-default-lib-path.patch
  build/python35/patches/22-disable-test_gdb.patch
  build/python35/patches/24-gethostname.patch
  build/python35/patches/25-test_site.patch
  build/python35/patches/26-getrandom.patch
  build/python35/patches/28-test-vmlimit.patch
  build/python35/patches/31-pty.patch
  build/python35/patches/avoid-runpath.patch
  build/python35/patches/dont-use-ccs.patch
  build/python35/patches/ncurses.patch
  build/python35/patches/socket.patch
  build/python35/patches/testsuite.patch
  build/python35/testsuite-d.log
  doc/packages.md
  lib/functions.sh
Labels: package update

#922 acpica: update to 20180810
  build/acpica/build.sh
  doc/packages.md
Labels: package update

#933 ntp: update to 4.2.8p12 (r151022)
  build/ntp/build.sh
Labels: backport-PR, package update

#932 ntp: update to 4.2.8p12 (r151024)
  build/ntp/build.sh
Labels: backport-PR, package update

#931 ntp: update to 4.2.8p12 (r151026)
  build/ntp/build.sh
Labels: backport-PR, package update

#930 openssl: update to 1.0.2p/1.1.0i (r151024)
  build/openssl/build.sh
Labels: backport-PR, package update

#929 ntp: update to 4.2.8p12
  build/ntp/build.sh
  build/ntp/patches/etcfix.patch
  build/ntp/patches/ins-ntpd.patch
  build/ntp/patches/no-arc4random-addrandom.patch
  build/ntp/patches/noextra.patch
  build/ntp/patches/series
  build/ntp/patches/timing.patch
  doc/packages.md
Labels: backport-todo, package update

#928 openssl: update to 1.0.2p/1.1.0i (r151026)
  build/openssl/build.sh
  build/openssl/patches-1.0/opensslconf.patch
  build/openssl/patches-1.0/pkcs11.patch
  build/openssl/patches-1.0/series
  build/openssl/patches-1.0/unused-dep.patch
  build/openssl/patches/libs.patch
  build/openssl/testsuite.log
Labels: backport-PR, package update

#927 openssl: update to 1.0.2p/1.1.0i
  build/openssl/build.sh
  build/openssl/patches-1.0/opensslconf.patch
  build/openssl/patches-1.0/pkcs11.patch
  build/openssl/patches-1.0/series
  build/openssl/patches-1.0/unused-dep.patch
  build/openssl/patches/libs.patch
  build/openssl/patches/rehash.patch
  build/openssl/patches/series
  build/openssl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#934 openssl: update to 1.0.2p (r151022)
  build/openssl/build.sh
Labels: backport-PR, package update

#921 pciutils: update to 3.6.2
  build/pciutils/build.sh
  doc/packages.md
Labels: package update

#943 openssh: patch for CVE-2018-15473 (r151022)
  build/openssh/patches/CVE-2018-15473.patch
  build/openssh/patches/series
Labels: backport-PR, package update

#942 openssh: patch for CVE-2018-15473 (r151024)
  build/openssh/patches/CVE-2018-15473.patch
  build/openssh/patches/series
Labels: backport-PR, package update

#941 openssh: patch for CVE-2018-15473 (r151026)
  build/openssh/patches/CVE-2018-15473.patch
  build/openssh/patches/series
Labels: backport-PR, package update

#940 openssh: patch for CVE-2018-15473
  build/openssh/patches/CVE-2018-15473.patch
  build/openssh/patches/series
Labels: backport-todo, package update

#939 openjdk: update to 1.7.0_191_b02
  build/openjdk/build.sh
  doc/packages.md
Labels: package update

#938 expat: update to 2.2.6
  build/expat/build.sh
  build/expat/testsuite.log
  doc/packages.md
Labels: package update

#945 cpuid: add support for L1D flush command
  build/cpuid/patches/l1df.patch
  build/cpuid/patches/series
Labels: package update

#950 ncurses: update to 20180818
  build/ncurses/build.sh
  build/ncurses/patches/extra-newline.patch
  build/ncurses/patches/xterm-no-rep.patch
  doc/packages.md
Labels: package update

#949 glib: update to 2.56.2
  build/glib/build.sh
  build/glib/patches/gobject.h.patch
  build/glib/patches/threadlib.patch
  build/glib/patches/zignore.patch
  build/glib/testsuite.log
  doc/packages.md
Labels: package update

#953 Update iso-codes and nghttp2 packages
  build/iso-codes/build.sh
  build/jeos/omnios-userland.pkg
  build/meta/omnios-build-tools.p5m
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  doc/packages.md
Labels: package update

#952 openssh: update to 7.8p1
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/openssh/build.sh
  build/openssh/patches/0001-Skip-config-check.patch
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0007-DTrace-support-for-SFTP.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0014-GSS-API-key-exchange-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/CVE-2018-15473.patch
  build/openssh/patches/openssl11-local.patch
  build/openssh/patches/openssl11.patch
  build/openssh/patches/series
  build/openssh/patches/sshd_config.patch
  build/openssh/testsuite.log
  doc/packages.md
  lib/functions.sh
Labels: package update

#956 cpuid: update to 1.6.5
  build/cpuid/build.sh
  build/cpuid/patches/l1df.patch
  build/cpuid/patches/series
  doc/packages.md
Labels: backport-todo, package update

#959 cpuid: update to 1.6.5 (r151022)
  build/cpuid/build.sh
Labels: backport-PR, package update

#958 cpuid: update to 1.6.5 (r151024)
  build/cpuid/build.sh
Labels: backport-PR, package update

#957 cpuid: update to 1.6.5 (r151026)
  build/cpuid/build.sh
  build/cpuid/patches/bhyve.patch
  build/cpuid/patches/series
Labels: backport-PR, package update

#962 bison: update to 3.1
  build/bison/build.sh
  build/bison/local.mog
  build/bison/testsuite.log
  build/jeos/omnios-userland.pkg
  doc/packages.md
Labels: package update

#961 ntpsec: update to 1.1.2 & add smf exclusions
  build/ntp/files/ntp.xml
  build/ntpsec/build.sh
  build/ntpsec/files/ntpsec.xml
  build/ntpsec/testsuite.log
  build/open-vm-tools/files/open-vm-tools.xml
  doc/packages.md
Labels: package update

#964 kvm: switch to our own forked mirrors (r151026)
  build/illumos-kvm/.gitignore
  build/illumos-kvm/OPENSOLARIS.LICENSE
  build/illumos-kvm/build.sh
  build/illumos-kvm/patches.illumos-kvm-cmd/build.sh.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/configure.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/ctf.sh.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/ncurses-include.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/remove-vnd.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/series
  build/illumos-kvm/patches.illumos-kvm/banquo.patch
  build/illumos-kvm/patches.illumos-kvm/series
Labels: review

#963 kvm: switch to our own forked mirrors
  build/illumos-kvm/.gitignore
  build/illumos-kvm/OPENSOLARIS.LICENSE
  build/illumos-kvm/build.sh
  build/illumos-kvm/patches.illumos-kvm-cmd/build.sh.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/configure.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/ctf.sh.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/ncurses-include.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/remove-vnd.patch
  build/illumos-kvm/patches.illumos-kvm-cmd/series
  build/illumos-kvm/patches.illumos-kvm/banquo.patch
  build/illumos-kvm/patches.illumos-kvm/series
Labels: review
