Repository omniosorg/omnios-build, pull requests merged in 2018-10, with the labels that each got.

#1022 Preparing for r151022bt
  build/release/root/etc/release
  doc/ReleaseNotes.md
Labels: review

#1033 Updating for r151028
  lib/config.sh
  tools/test
Labels: review

#1035 hg: update to 4.7.2
  build/mercurial/build.sh
  doc/packages.md
Labels: backport-todo, package update, review

#1034 Use $RELVER for building miniroot
  build/kayak-kernel/build.sh
  build/kayak-kernel/sudo-bits.sh
Labels: review

#1036 hg: update to 4.7.2 (r151028)
  build/mercurial/build.sh
  doc/packages.md
Labels: backport-PR, review

#1038 hg: Fix a potential out-of-bounds read in manifest parsing C code. (r…
  build/mercurial/patches/CVE-2018-13348.patch
  build/mercurial/patches/out_of_bounds.patch
  build/mercurial/patches/rewrite_pathlen.patch
  build/mercurial/patches/series
Labels: review, security

#1037 hg: Fix a potential out-of-bounds read in manifest parsing C code. (r…
  build/mercurial/patches/out_of_bounds.patch
  build/mercurial/patches/rewrite_pathlen.patch
  build/mercurial/patches/series
Labels: review, security

#1039 openssh: fixing download URL
  doc/packages.md
Labels: review

#1041 Restore legacy libraries (r151028)
  build/libidn/build.sh
  build/net-snmp/build.sh
Labels: review

#1040 Restore legacy libraries
  build/libidn/build.sh
  build/net-snmp/build.sh
Labels: backport-todo, review

#1044 git: update to 2.17.2 (r151026)
  build/git/build.sh
  build/git/testsuite.log
Labels: backport-PR, package update, security

#1043 git: update to 2.19.1 (r151028)
  build/git/build.sh
Labels: backport-PR, package update, security

#1042 git: update to 2.19.1
  build/git/build.sh
  doc/packages.md
Labels: backport-todo, package update, security

#1046 git: update to 2.14.5 (r151024)
  build/git/build.sh
  build/git/testsuite.log
Labels: backport-PR, package update, security

#1045 hg: Fix a potential out-of-bounds read in manifest parsing C code. (r…
  build/mercurial/patches/out_of_bounds.patch
  build/mercurial/patches/rewrite_pathlen.patch
  build/mercurial/patches/series
Labels: backport-PR, security

#1070 bmake: update to 20180919
  build/bmake/build.sh
  doc/packages.md
Labels: package update

#1069 nghttp2: update to 1.34
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  doc/packages.md
Labels: package update

#1080 package updates
  build/acpica/build.sh
  build/bind/build.sh
  build/fio/build.sh
  doc/packages.md
Labels: package update
