Repository omniosorg/omnios-build, pull requests merged in 2019-06, with the labels that each got.

#1429 perl: update to 5.30.0
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/perl/build.sh
  build/perl/patches/dtrace.patch
  build/perl/patches/patch-hints_solaris__2.sh
  build/perl/patches/t_op_getppid.t.patch
  build/perl/testsuite.log
  build/perl/testsuite64.log
  doc/packages.md
Labels: package update

#1434 package updates
  build/jeos/omnios-userland.pkg
  build/ncurses/build.sh
  build/ncurses/patches/extra-newline.patch
  build/ncurses/patches/sun-color.patch
  build/ncurses/patches/xterm-no-rep.patch
  build/python35/cryptography/build.sh
  build/python35/mako/build.sh
  doc/packages.md
Labels: package update

#1435 curl: update to 7.65.1
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#1436 curl: update to 7.65.1 (r151030)
  build/curl/build.sh
Labels: backport-PR, package update

#1437 curl: update to 7.65.1 (r151028)
  build/curl/build.sh
Labels: backport-PR, package update

#1438 curl: update to 7.65.1 (r151022)
  build/curl/build.sh
Labels: backport-PR, package update

#1442 vim: Disallow sourcing a file from the sandbox (r151022)
  build/vim/patches/series
  build/vim/patches/vim-sandbox.patch
Labels: backport-PR, package update

#1441 vim: Disallow sourcing a file from the sandbox (r151028)
  build/vim/patches/series
  build/vim/patches/vim-sandbox.patch
Labels: backport-PR, package update

#1443 hg: update to 5.0.1
  build/mercurial/build.sh
  doc/packages.md
Labels: package update

#1447 git: upate to 2.22.0
  build/git/build.sh
  build/git/testsuite.log
  doc/packages.md
Labels: package update

#1449 package updates
  build/cpuid/build.sh
  build/cpuid/patches/21.diff
  build/cpuid/patches/series
  build/dbus/build.sh
  build/dbus/testsuite.log
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  build/python35/mako/build.sh
  build/python35/portend/build.sh
  doc/packages.md
Labels: package update

#1454 package updates
  build/gawk/build.sh
  build/gawk/testsuite.log
  build/python35/meson/build.sh
  build/python35/meson/patches/illumos_gcc.patch
  build/sigcpp/build.sh
  build/sigcpp/local.mog
  build/sigcpp/testsuite.log
  doc/packages.md
Labels: package update

#1457 expat: update to 2.2.7
  build/expat/build.sh
  build/expat/local.mog
  build/expat/patches/manpage.patch
  build/expat/patches/series
  build/expat/patches/unwind.patch
  build/expat/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#1458 expat: update to 2.2.7 (r151030)
  build/expat/build.sh
  build/expat/local.mog
  build/expat/patches/series
  build/expat/patches/unwind.patch
Labels: backport-PR, package update

#1459 expat: update to 2.2.7 (r151028)
  build/expat/build.sh
  build/expat/local.mog
  build/expat/patches/series
  build/expat/patches/unwind.patch
Labels: backport-PR, package update

#1460 expat: Fix security bug (r151022)
  build/expat/local.mog
  build/expat/patches/security-186.patch
  build/expat/patches/series
Labels: backport-PR, package update

#1465 azure agent: update to 2.2.41
  build/azure/build.sh
  doc/packages.md
Labels: backport-todo, package update

#1464 azure agent: update to 2.2.41 (r151030)
  build/azure/build.sh
Labels: package update

#1467 package updates
  build/mozilla-nss-nspr/build.sh
  build/ntpsec/build.sh
  build/ntpsec/patches/conf.patch
  build/ntpsec/patches/mansections.patch
  build/ntpsec/patches/pie.patch
  build/ntpsec/testsuite.log
  build/python35/cherrypy/build.sh
  build/python35/pycurl/build.sh
  doc/packages.md
Labels: package update

#1472 bzip2: update to 1.0.7 (r151022)
  build/bzip2/build.sh
  build/bzip2/local.mog
  build/bzip2/patches/CVE-2016-3189.patch
  build/bzip2/patches/Makefile.patch
  build/bzip2/patches/selectors.patch
  build/bzip2/patches/series
  build/entire/entire.p5m
  build/jeos/omnios-userland.p5m
Labels: backport-PR, package update

#1471 bzip2: update to 1.0.7 (r151028)
  build/bzip2/build.sh
  build/bzip2/local.mog
  build/bzip2/patches/CVE-2016-3189.patch
  build/bzip2/patches/Makefile.patch
  build/bzip2/patches/selectors.patch
  build/bzip2/patches/series
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
Labels: backport-PR, package update

#1470 bzip2: update to 1.0.7 (r151030)
  build/bzip2/build.sh
  build/bzip2/local.mog
  build/bzip2/patches/CVE-2016-3189.patch
  build/bzip2/patches/Makefile.patch
  build/bzip2/patches/selectors.patch
  build/bzip2/patches/series
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
Labels: backport-PR, package update
