Repository omniosorg/omnios-build, pull requests merged in 2019-12, with the labels that each got.

#1671 openjdk8: update to 1.8.232-09 (r30)
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_jsig.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  tools/test
Labels: backport-PR, package update

#1670 openjdk8: update to 1.8.232-09 (r32)
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_jsig.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  tools/test
Labels: backport-PR, package update

#1668 openjdk8: update to 1.8.232-09
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_jsig.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  doc/packages.md
  tools/test
Labels: backport-todo, package update

#1667 package updates
  build/jeos/omnios-userland.pkg
  build/obsolete/python-37/jaraco.functools-37.p5m
  build/python37/README
  build/python37/cherrypy/build.sh
  build/python37/jaraco/build.sh
  build/python37/jaraco/local.mog
  build/python37/meson/build.sh
  build/python37/more-itertools/build.sh
  build/python37/tempora/build.sh
  build/tcsh/build.sh
  build/tmux/build.sh
  doc/baseline
  doc/packages.md
  lib/functions.sh
  tools/test
Labels: package update

#1673 package updates
  build/jeos/omnios-userland.pkg
  build/python37/importlib-metadata/build.sh
  build/python37/jaraco/build.sh
  build/python37/setuptools/build.sh
  build/tcsh/build.sh
  build/tcsh/testsuite.log
  doc/packages.md
Labels: package update

#1677 package updates
  build/mercurial/build.sh
  build/mozilla-nss-nspr/build.sh
  build/python37/importlib-metadata/build.sh
  build/python37/more-itertools/build.sh
  build/tcsh/build.sh
  build/tcsh/testsuite.log
  doc/packages.md
Labels: package update

#1683 use current cups headers to build openjdk (r30)
  build/openjdk8/build.sh
Labels: backport-PR

#1682 use current cups headers to build openjdk (r32)
  build/openjdk8/build.sh
Labels: backport-PR

#1681 use current cups headers to build openjdk
  build/openjdk8/build.sh
Labels: backport-todo

#1685 package updates
  build/bind/build.sh
  build/fio/build.sh
  doc/packages.md
Labels: package update

#1691 openssl: update to 1.0.2u (r151032)
  build/openssl/build.sh
Labels: backport-PR, package update

#1690 openssl: update to 1.0.2u
  build/openssl/build.sh
  doc/packages.md
Labels: backport-todo, package update

#1693 openssl: update to 1.0.2u (r151022)
  build/openssl/build.sh
  build/release/root/etc/release
  doc/ReleaseNotes.md
Labels: backport-PR, package update

#1692 openssl: update to 1.0.2u (r151030)
  build/openssl/build.sh
Labels: backport-PR, package update

#1694 package updates
  build/glib/build.sh
  build/jeos/omnios-userland.pkg
  build/python37/build.sh
  build/python37/coverage/build.sh
  build/python37/importlib-metadata/build.sh
  build/python37/jaraco/build.sh
  build/python37/tempora/build.sh
  build/python37/testsuite-d.log
  build/python37/testsuite.log
  doc/packages.md
Labels: package update
