Repository omniosorg/omnios-build, pull requests merged in 2019-09, with the labels that each got.

#1535 Package updates
  build/bash/build.sh
  build/bash/patches/bash-5.0-patches/bash50-010
  build/bash/patches/bash-5.0-patches/bash50-011
  build/bash/patches/series
  build/entire/entire.pkg
  build/findutils/build.sh
  build/findutils/testsuite.log
  build/jeos/omnios-userland.pkg
  build/ncurses/build.sh
  doc/packages.md
Labels: package update

#1537 package updates
  build/glib/build.sh
  build/mozilla-nss-nspr/build.sh
  build/python35/meson/build.sh
  doc/packages.md
Labels: package update

#1540 ntpsec: update to 1.1.7
  build/ntpsec/build.sh
  build/ntpsec/patches/conf.patch
  build/ntpsec/patches/mansections.patch
  doc/packages.md
Labels: package update

#1541 package updates
  build/entire/entire.pkg
  build/glib/build.sh
  build/glib/testsuite.log
  build/jeos/omnios-userland.pkg
  build/mercurial/build.sh
  build/python35/cheroot/build.sh
  build/python35/cherrypy/build.sh
  build/sigcpp/build.sh
  build/sigcpp/testsuite.log
  doc/packages.md
Labels: package update

#1544 nss: udpate to 3.46; nspr: update to 4.22 (r151028)
  build/mozilla-nss-nspr/build.sh
Labels: backport-PR, package update

#1545 nss: udpate to 3.46; nspr: update to 4.22 (r151022)
  build/entire/entire.p5m
  build/jeos/omnios-userland.p5m
  build/mozilla-nss-nspr/build.sh
Labels: backport-PR, package update

#1551 Add rxvt-unicode terminfo to ncurses (r151030)
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/urxvt/build.sh
  build/urxvt/local.mog
  doc/baseline
Labels: backport-PR, package update

#1552 openssl: update to 1.1.1d/1.0.2t
  build/openssl/build.sh
  doc/packages.md
Labels: backport-todo, package update

#1555 openssl: update to 1.0.2t (r151022)
  build/openssl/build.sh
Labels: backport-PR, package update

#1556 curl: update to 7.66.0
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#1558 curl: update to 7.66.0 (r151028)
  build/curl/build.sh
Labels: backport-PR, package update

#1559 curl: update to 7.66.0 (r151022)
  build/curl/build.sh
Labels: backport-PR, package update

#1570 expat: update to 2.2.8
  build/expat/build.sh
  doc/packages.md
Labels: backport-todo, package update

#1571 expat: update to 2.2.8 (r151030)
  build/expat/build.sh
Labels: backport-PR, package update

#1572 expat: update to 2.2.8 (r151028)
  build/expat/build.sh
Labels: backport-PR, package update

#1573 expat: Add patch for CVE-2019-15903 (r151022)
  build/expat/patches/CVE-2019-15903.patch
  build/expat/patches/series
Labels: backport-PR, package update

#1585 package updates
  build/bind/build.sh
  build/fio/build.sh
  build/fio/patches/Makefile.patch
  build/fio/patches/fio2gnuplot.patch
  build/jeos/omnios-userland.pkg
  build/ncurses/build.sh
  build/python35/contextlib2/build.sh
  doc/packages.md
Labels: package update
