Repository omniosorg/omnios-build, pull requests merged in 2020-07, with the labels that each got.

#1931 omnios-build Package updates
  build/curl/build.sh
  build/curl/testsuite.log
  build/mercurial/build.sh
  build/mozilla-nss-nspr/build.sh
  build/nasm/build.sh
  build/python37/idna/build.sh
  build/python37/importlib-metadata/build.sh
  build/python37/more-itertools/build.sh
  doc/packages.md
Labels: package update

#1939 curl: update to 7.71.1
  build/curl/build.sh
  build/curl/patches/CVE-2020-8169.patch
  build/curl/patches/CVE-2020-8177.patch
  build/curl/patches/series
  build/curl/testsuite.log
Labels: backport-PR

#1941 package updates
  build/jeos/omnios-userland.pkg
  build/libmpfr/build.sh
  build/libmpfr/testsuite.log
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/demangle.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_saproc.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_posix_vm_os__posix.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__Makefile.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__saproc.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_decoder__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_utilities_globalDefinitions__gcc.hpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_bin_ergo__i586.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
  build/rsync/build.sh
  build/rsync/testsuite.log
  doc/packages.md
  lib/config.sh
Labels: backport-todo, package update

#1944 backports to r151030
  build/jeos/omnios-userland.pkg
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/jdk.mog
  build/openjdk8/jre.mog
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_saproc.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_posix_vm_os__posix.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_decoder__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_utilities_globalDefinitions__gcc.hpp.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_bin_ergo__i586.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
  build/rsync/build.sh
  build/rsync/testsuite.log
  lib/config.sh
Labels: backport-PR

#1943 backports to r151032
  build/jeos/omnios-userland.pkg
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/jdk.mog
  build/openjdk8/jre.mog
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_saproc.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_posix_vm_os__posix.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_decoder__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_utilities_globalDefinitions__gcc.hpp.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_bin_ergo__i586.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
  build/rsync/build.sh
  build/rsync/testsuite.log
  lib/config.sh
Labels: backport-PR

#1942 backports to r151034
  build/jeos/omnios-userland.pkg
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/demangle.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_saproc.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_posix_vm_os__posix.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__Makefile.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__saproc.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_decoder__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_utilities_globalDefinitions__gcc.hpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_bin_ergo__i586.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
  build/rsync/build.sh
  build/rsync/testsuite.log
  lib/config.sh
Labels: backport-PR
