Repository omniosorg/omnios-build, pull requests merged in 2020-04, with the labels that each got.

#1786 openssl: update to 1.1.1f (r151030)
  build/openssl/build.sh
Labels: backport-PR, package update

#1785 openssl: update to 1.1.1f (r151032)
  build/openssl/build.sh
Labels: backport-PR, package update

#1783 openssl: update to 1.1.1f
  build/openssl/build.sh
  doc/packages.md
Labels: backport-todo, package update

#1784 openssl: update to 1.1.1f (r151034)
  build/openssl/build.sh
Labels: backport-PR, package update

#1799 package updates
  build/bison/build.sh
  build/bison/testsuite.log
  build/jeos/omnios-userland.pkg
  build/mercurial/build.sh
  build/python37/cryptography/build.sh
  build/python37/importlib-metadata/build.sh
  build/python37/meson/build.sh
  doc/packages.md
  lib/functions.sh
Labels: package update

#1800 package updates
  build/glib/build.sh
  build/glib/testsuite.log
  build/mozilla-nss-nspr/build.sh
  doc/packages.md
Labels: package update

#1812 package updates (r151034)
  build/bind/build.sh
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/demangle.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_saproc.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__Makefile.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__saproc.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_decoder__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/series
Labels: backport-PR, package update

#1820 openssl: update to 1.1.1g (r151030)
  build/openssl/build.sh
  build/openssl/testsuite.log
  build/python27/build.sh
  build/python27/patches/disable_epoll.patch
  build/python27/patches/series
  build/python27/testsuite-32.log
  build/python27/testsuite.log
  build/python35/patches/disable_epoll.patch
  build/python35/patches/series
  build/python35/testsuite-d.log
  build/python35/testsuite.log
Labels: backport-PR, package update

#1821 openssl: update to 1.1.1g (r151032)
  build/openssl/build.sh
  build/openssl/testsuite.log
  build/python27/build.sh
  build/python27/patches/disable_epoll.patch
  build/python27/patches/series
  build/python27/testsuite-32.log
  build/python27/testsuite.log
  build/python37/patches/disable_epoll.patch
  build/python37/patches/series
  build/python37/testsuite-d.log
  build/python37/testsuite.log
Labels: backport-PR, package update

#1822 openssl: update to 1.1.1g (r151034)
  build/openssl/build.sh
  build/openssl/testsuite.log
  build/python27/build.sh
  build/python27/patches/disable_epoll.patch
  build/python27/patches/series
  build/python27/testsuite-32.log
  build/python27/testsuite.log
  build/python37/patches/disable_epoll.patch
  build/python37/patches/series
  build/python37/testsuite-d.log
  build/python37/testsuite.log
Labels: backport-PR, package update

#1826 git: update to 2.26.2
  build/git/build.sh
  doc/packages.md
Labels: backport-todo, package update

#1829 git: update to 2.17.5 (r151022)
  build/git/build.sh
  build/jeos/omnios-userland.p5m
Labels: package update

#1828 git: update to 2.21.3 (r151030)
  build/git/build.sh
Labels: package update

#1827 git: update to 2.23.3 (r151032)
  build/git/build.sh
Labels: package update

#1832 package updates
  build/bash/build.sh
  build/bash/patches/bash-5.0-patches/bash50-017
  build/bash/patches/series
  build/python37/cherrypy/build.sh
  build/python37/coverage/build.sh
  build/python37/cryptography/build.sh
  build/python37/jsonrpclib/build.sh
  doc/packages.md
Labels: package update
