Repository omniosorg/omnios-build, pull requests merged in 2020-12, with the labels that each got.

#2123 package updates
  build/sqlite3/build.sh
  build/sudo/build.sh
  build/sudo/testsuite.log
  doc/packages.md
  lib/functions.sh
Labels: package update

#2131 OpenSSL updates (r151036)
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2020-1968.patch
  build/openssl/patches-1.0/CVE-2020-1971.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite.log
Labels: backport-PR, security

#2130 OpenSSL updates
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2020-1968.patch
  build/openssl/patches-1.0/CVE-2020-1971.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite.log
  doc/packages.md
Labels: backport-todo, security

#2132 OpenSSL Updates (r151034)
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2020-1968.patch
  build/openssl/patches-1.0/CVE-2020-1971.patch
  build/openssl/patches-1.0/series
Labels: backport-PR, security

#2133 OpenSSL Updates (r151030)
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2020-1968.patch
  build/openssl/patches-1.0/CVE-2020-1971.patch
  build/openssl/patches-1.0/series
Labels: backport-PR, security

#2135 curl: update to 7.74.0 (r151036)
  build/curl/build.sh
  build/curl/patches/tests.patch
Labels: backport-PR, security

#2137 curl: update to 7.74.0 (r151030)
  build/curl/build.sh
  build/curl/patches/CVE-2020-8169.patch
  build/curl/patches/CVE-2020-8177.patch
  build/curl/patches/CVE-2020-8231.patch
  build/curl/patches/series
  build/curl/patches/tests.patch
Labels: backport-PR, security

#2134 curl: update to 7.74.0
  build/curl/build.sh
  build/curl/patches/tests.patch
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, security

#2136 curl: update to 7.74.0 (r151034)
  build/curl/build.sh
  build/curl/patches/CVE-2020-8231.patch
  build/curl/patches/series
  build/curl/patches/tests.patch
Labels: backport-PR, security

#2138 package updates
  build/autoconf/build.sh
  build/autoconf/local.mog
  build/autoconf/testsuite.log
  build/jeos/omnios-userland.pkg
  build/mozilla-nss-nspr/build.sh
  build/python39/build.sh
  build/python39/patches/CVE-2020-27619.patch
  build/python39/patches/SOABI.patch
  build/python39/patches/cgiserver.patch
  build/python39/patches/default-lib-path.patch
  build/python39/patches/disable_epoll.patch
  build/python39/patches/dont-use-ccs.patch
  build/python39/patches/enable-ossaudiodev.patch
  build/python39/patches/locale-encoding.patch
  build/python39/patches/mod-posix-sched_priority.patch
  build/python39/patches/mod-posix-sendfile.patch
  build/python39/patches/mod-shutil-sendfile.patch
  build/python39/patches/mod-socket-xpg6.patch
  build/python39/patches/mod-time-threadtime.patch
  build/python39/patches/module-dlpi.patch
  build/python39/patches/module-py_db.patch
  build/python39/patches/module-ucred.patch
  build/python39/patches/no-zip-in-sys-path.patch
  build/python39/patches/series
  build/python39/patches/setup.patch
  build/python39/patches/strxfrm-fix.patch
  build/python39/patches/test-pkgutil.patch
  build/rsyslog/build.sh
  build/rsyslog/testsuite.log
  doc/packages.md
Labels: package update

#2140 bind: update to 9.16.10
  build/bind/build.sh
  build/bind/files/ctf.ignore
  build/bind/local.mog
  build/bind/patches/libs.patch
  build/bind/patches/linker_flags.patch
  build/bind/patches/series
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  doc/packages.md
  lib/mog/global-transforms.mog
Labels: package update

#2143 sudo: update to 1.9.4p1
  build/sudo/build.sh
  doc/packages.md
Labels: package update

#2145 package updates
  build/bash/build.sh
  build/bash/patches/bash-5.1-patches/bash51-001
  build/bash/patches/bash-5.1-patches/bash51-002
  build/bash/patches/bash-5.1-patches/bash51-003
  build/bash/patches/bash-5.1-patches/bash51-004
  build/bash/patches/parallel.patch
  build/bash/patches/series
  build/sudo/build.sh
  doc/packages.md
Labels: package update

#2147 package updates
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/python39/cheroot/build.sh
  build/python39/coverage/build.sh
  build/python39/jaraco/build.sh
  build/python39/orjson/build.sh
  build/python39/pyopenssl/build.sh
  build/python39/pytz/build.sh
  build/python39/rapidjson/build.sh
  build/python39/setuptools/build.sh
  doc/packages.md
Labels: package update
