Repository omniosorg/omnios-build, pull requests merged in 2020-10, with the labels that each got.

#2049 glib2: update to 2.66.1
  build/glib/build.sh
  doc/packages.md
Labels: package update

#2063 gcc10: Fix problem with builtin memcmp() (r151036)
  build/gcc10/patches/bug_95189_builtin_memcmp.patch
  build/gcc10/patches/series
Labels: backport-PR

#2080 openjdk8: update to 1.8.272-10 (r151030)
  build/openjdk8/build.sh
Labels: backport-PR, security

#2079 openjdk8: update to 1.8.272-10 (r151032)
  build/openjdk8/build.sh
Labels: backport-PR, security

#2078 openjdk8: update to 1.8.272-10 (r151034)
  build/openjdk8/build.sh
Labels: backport-PR, security

#2077 openjdk updates (r151036)
  build/openjdk11/build.sh
  build/openjdk8/build.sh
Labels: backport-PR, security

#2076 openjdk updates
  build/openjdk11/build.sh
  build/openjdk8/build.sh
  doc/packages.md
Labels: backport-todo, package update, security
