Repository omniosorg/omnios-build, pull requests merged in 2021-11, with the labels that each got.

#2560 cloudinit: update to 21.4
  build/cloud-init/build.sh
  doc/packages.md
Labels: package update

#2564 python39 - update from 3.9.7 to 3.9.8 (r151038)
  build/python39/build.sh
  build/python39/patches/disable_epoll.patch
  build/python39/patches/mod-posix-sched_priority.patch
  build/python39/patches/mod-time-threadtime.patch
  build/python39/patches/module-dlpi.patch
  build/python39/patches/module-priv-rbac.patch
  build/python39/patches/module-py_db.patch
  build/python39/patches/module-ucred.patch
  build/python39/patches/no-zip-in-sys-path.patch
  build/python39/patches/series
  build/python39/patches/test-vmlimit.patch
Labels: package update, backport-PR

#2565 python39 - update from 3.9.7 to 3.9.8 (r151040)
  build/python39/build.sh
  build/python39/patches/disable_epoll.patch
  build/python39/patches/mod-time-threadtime.patch
  build/python39/patches/module-dlpi.patch
  build/python39/patches/module-priv-rbac.patch
  build/python39/patches/module-py_db.patch
  build/python39/patches/module-ucred.patch
  build/python39/patches/no-zip-in-sys-path.patch
  build/python39/patches/series
  build/python39/patches/test-vmlimit.patch
Labels: package update, backport-PR

#2563 Core package updates
  build/automake/build.sh
  build/automake/testsuite.log
  build/gawk/build.sh
  build/gawk/testsuite.log
  build/glib/build.sh
  build/glib/patches/gobject.h.patch
  build/glib/patches/libsocket.patch
  build/glib/patches/no_inotify.patch
  build/glib/testsuite.log
  build/mercurial/build.sh
  build/mozilla-nss-nspr/build.sh
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  build/python39/build.sh
  build/python39/patches/disable_epoll.patch
  build/python39/patches/mod-time-threadtime.patch
  build/python39/patches/module-dlpi.patch
  build/python39/patches/module-priv-rbac.patch
  build/python39/patches/module-py_db.patch
  build/python39/patches/module-ucred.patch
  build/python39/patches/no-zip-in-sys-path.patch
  build/python39/patches/series
  build/python39/patches/test-vmlimit.patch
  build/python39/testsuite.log
  build/socat/build.sh
  build/socat/patches/getprotobynumber_r_compat.patch
  build/socat/patches/series
  build/socat/patches/tcp_info.patch
  doc/packages.md
Labels: package update, backport-todo

#2573 Additional openjdk17 patches (r151040)
  build/openjdk17/patches/illumos-port-12.patch
  build/openjdk17/patches/illumos-port-13.patch
  build/openjdk17/patches/illumos-port-14.patch
  build/openjdk17/patches/series
Labels: backport-PR

#2571 net-snmp: fix library only builds (r151040)
  build/net-snmp/build.sh
  build/net-snmp/testsuite.log
Labels: backport-PR

#2570 net-snmp: fix library only builds
  build/net-snmp/build.sh
  build/net-snmp/testsuite.log
Labels: backport-todo

#2572 net-snmp: fix library only builds (r151038)
  build/net-snmp/build.sh
Labels: backport-PR

#2583 vim: update to 8.2.3582 (r151040)
  build/vim/build.sh
  build/vim/files/ftdetect/p5m.vim
  build/vim/files/ftplugin/p5m.vim
  build/vim/files/syntax/p5m.vim
  build/vim/local.mog
Labels: package update, backport-PR

#2582 vim: update to 8.2.3582
  build/vim/build.sh
Labels: package update, backport-todo

#2584 vim: update to 8.2.3582 (r151038)
  build/vim/build.sh
  build/vim/files/ftdetect/p5m.vim
  build/vim/files/ftplugin/p5m.vim
  build/vim/files/syntax/p5m.vim
  build/vim/local.mog
Labels: package update, backport-PR

#2595 bash: update to 5.1.12
  build/bash/build.sh
  build/bash/patches/bash-5.1-patches/bash51-009
  build/bash/patches/bash-5.1-patches/bash51-010
  build/bash/patches/bash-5.1-patches/bash51-011
  build/bash/patches/bash-5.1-patches/bash51-012
  build/bash/patches/series
  doc/packages.md
Labels: package update

#2601 python39 - update from 3.9.8 to 3.9.9 (r151040)
  build/python39/build.sh
Labels: package update, backport-PR

#2600 python39 - update from 3.9.8 to 3.9.9 (r151038)
  build/python39/build.sh
Labels: package update, backport-PR

#2599 python39 - update from 3.9.8 to 3.9.9
  build/python39/build.sh
  doc/packages.md
Labels: package update, backport-todo
