Repository omniosorg/omnios-build, pull requests merged in 2021-02, with the labels that each got.

#2194 Core package updates
  build/binutils/build.sh
  build/curl/build.sh
  build/curl/testsuite.log
  build/git/build.sh
  build/git/testsuite.log
  build/glib/build.sh
  build/glib/testsuite.log
  build/mercurial/build.sh
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  doc/packages.md
Labels: package update

#2195 screen: add patch for CVE-2021-26937
  build/screen/patches/CVE-2021-26937.patch
  build/screen/patches/series
Labels: backport-todo

#2196 screen: add patch for CVE-2021-26937 (r151036)
  build/screen/patches/CVE-2021-26937.patch
  build/screen/patches/series
Labels: backport-PR, package update

#2197 screen: add patch for CVE-2021-26937 (r151034)
  build/screen/patches/CVE-2021-26937.patch
  build/screen/patches/series
Labels: backport-PR, package update

#2198 screen: add patch for CVE-2021-26937 (r151030)
  build/screen/patches/CVE-2021-26937.patch
  build/screen/patches/series
Labels: backport-PR, package update

#2208 python: fixes for CVE-2021-3177
  build/python27/patches/CVE-2021-3177.patch
  build/python27/patches/series
  build/python39/patches/CVE-2021-3177.patch
  build/python39/patches/series
Labels: backport-todo, package update

#2209 python: fixes for CVE-2021-3177 (r151030)
  build/python27/patches/CVE-2021-3177.patch
  build/python27/patches/series
  build/python35/patches/CVE-2021-3177.patch
  build/python35/patches/series
Labels: backport-PR, package update

#2207 python: fixes for CVE-2021-3177 (r151034)
  build/python27/patches/CVE-2021-3177.patch
  build/python27/patches/series
  build/python37/patches/CVE-2021-3177.patch
  build/python37/patches/series
Labels: backport-PR, package update

#2206 python: fixes for CVE-2021-3177 (r151036)
  build/python27/patches/CVE-2021-3177.patch
  build/python27/patches/series
  build/python37/patches/CVE-2021-3177.patch
  build/python37/patches/series
Labels: backport-PR, package update

#2214 Python3: update to 3.7.10 (r151034)
  build/python37/build.sh
  build/python37/patches/14-default-lib-path.patch
  build/python37/patches/CVE-2020-14422.patch
  build/python37/patches/CVE-2020-20907.patch
  build/python37/patches/CVE-2020-27619.patch
  build/python37/patches/CVE-2021-3177.patch
  build/python37/patches/dont-use-ccs.patch
  build/python37/patches/series
Labels: package update

#2213 Python3: update to 3.7.10 (r151036)
  build/python37/build.sh
  build/python37/patches/14-default-lib-path.patch
  build/python37/patches/CVE-2020-27619.patch
  build/python37/patches/CVE-2021-3177.patch
  build/python37/patches/dont-use-ccs.patch
  build/python37/patches/series
Labels: package update

#2218 openssl: update to 1.1.1j (r151030)
  build/openssl/build.sh
Labels: backport-PR, package update

#2217 openssl: update to 1.1.1j (r151034)
  build/openssl/build.sh
Labels: backport-PR, package update

#2216 openssl: update to 1.1.1j (r151036)
  build/openssl/build.sh
Labels: backport-PR, package update

#2215 openssl: update to 1.1.1j
  build/openssl/build.sh
  build/openssl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#2226 openssl 1.0.2: patch CVE-2021-23840 and CVE-2021-23841 (r151034)
  build/openssl/patches-1.0/CVE-2021-23840-pre2.patch
  build/openssl/patches-1.0/CVE-2021-23840.patch
  build/openssl/patches-1.0/CVE-2021-23841.patch
  build/openssl/patches-1.0/series
Labels: backport-PR, security

#2227 openssl 1.0.2: patch CVE-2021-23840 and CVE-2021-23841 (r151030)
  build/openssl/patches-1.0/CVE-2021-23840-pre2.patch
  build/openssl/patches-1.0/CVE-2021-23840.patch
  build/openssl/patches-1.0/CVE-2021-23841.patch
  build/openssl/patches-1.0/series
Labels: backport-PR, security

#2224 openssl 1.0.2: patch CVE-2021-23840 and CVE-2021-23841
  build/openssl/patches-1.0/CVE-2021-23840-pre2.patch
  build/openssl/patches-1.0/CVE-2021-23840.patch
  build/openssl/patches-1.0/CVE-2021-23841.patch
  build/openssl/patches-1.0/series
Labels: backport-todo, security

#2229 Python 3.9: update to 3.9.2
  build/python39/build.sh
  build/python39/patches/CVE-2021-3177.patch
  build/python39/patches/SOABI.patch
  build/python39/patches/cgiserver.patch
  build/python39/patches/gid-convert.patch
  build/python39/patches/mod-posix-sched_priority.patch
  build/python39/patches/module-priv-rbac.patch
  build/python39/patches/series
  doc/packages.md
Labels: package update

#2232 Core package updates
  build/bind/build.sh
  build/gtar/build.sh
  build/gtar/patches/revert_check_return_value_from_xgetcwd.patch
  build/gtar/patches/series
  build/gtar/testsuite.log
  build/libedit/build.sh
  build/libedit/patches/gawk.patch
  build/libedit/patches/ncurses.patch
  build/mozilla-nss-nspr/build.sh
  build/rsyslog/build.sh
  build/rsyslog/testsuite.log
  doc/packages.md
Labels: package update
