Repository omniosorg/omnios-build, pull requests merged in 2021-04, with the labels that each got.

#2284 curl: update to 7.76.0 (r151030)
  build/curl/build.sh
  build/curl/patches/tests.patch
  build/curl/testsuite.log
Labels: backport-PR, package update, security

#2283 curl: update to 7.76.0 (r151034)
  build/curl/build.sh
  build/curl/patches/tests.patch
  build/curl/testsuite.log
Labels: backport-PR, package update, security

#2282 curl: update to 7.76.0
  build/curl/build.sh
  build/curl/patches/tests.patch
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, security

#2281 curl: update to 7.76.0 (r151038)
  build/curl/build.sh
  build/curl/patches/tests.patch
  build/curl/testsuite.log
Labels: backport-PR, package update, security

#2280 curl: update to 7.76.0 (r151036)
  build/curl/build.sh
  build/curl/patches/tests.patch
  build/curl/testsuite.log
Labels: backport-PR, package update, security

#2315 curl: update to 7.76.1 (r151038)
  build/curl/build.sh
Labels: backport-PR, package update

#2316 curl: update to 7.76.1 (r151036)
  build/curl/build.sh
Labels: backport-PR, package update

#2317 curl: update to 7.76.1 (r151034)
  build/curl/build.sh
Labels: backport-PR, package update

#2318 curl: update to 7.76.1 (r151030)
  build/curl/build.sh
Labels: backport-PR, package update

#2314 curl: update to 7.76.1
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update
