Repository omniosorg/omnios-build, pull requests merged in 2021-08, with the labels that each got.

#2432 diffutils - update from 3.7 to 3.8
  build/diffutils/build.sh
  build/diffutils/testsuite.log
  doc/packages.md
Labels: package update

#2437 perl: patch Encoding to address CVE-2021-36770
  build/perl/patches/CVE-2021-36770.patch
  build/perl/patches/series
Labels: backport-todo, security

#2436 perl: patch Encoding to address CVE-2021-36770 (r151036)
  build/jeos/omnios-userland.pkg
  build/perl/build.sh
  build/perl/patches/CVE-2021-36770.patch
  build/perl/patches/series
Labels: security, backport-PR

#2435 perl: patch Encoding to address CVE-2021-36770 (r151038)
  build/perl/build.sh
  build/perl/patches/CVE-2021-36770.patch
  build/perl/patches/series
Labels: security, backport-PR

#2448 core package updates
  build/bind/build.sh
  build/git/build.sh
  build/git/testsuite.log
  build/glib/build.sh
  build/glib/testsuite.log
  build/mozilla-nss-nspr/build.sh
  build/python39/jaraco/build.sh
  build/python39/mako/build.sh
  build/python39/meson/build.sh
  build/python39/meson/patches/compiler_def_static_linker.patch
  build/python39/orjson/build.sh
  build/python39/pip/build.sh
  build/python39/pycurl/build.sh
  build/python39/setuptools/build.sh
  doc/packages.md
Labels: package update

#2449 openssl updates
  build/openssl/build-1.1.sh
  build/openssl/patches-1.0/CVE-2021-3712.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite-1.1.log
  doc/packages.md
Labels: backport-todo, security

#2450 openssl updates (r151038)
  build/openssl/build-1.1.sh
  build/openssl/patches-1.0/CVE-2021-3712.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite-1.1.log
Labels: security, backport-PR

#2451 openssl updates (r151036)
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2021-3712.patch
  build/openssl/patches-1.0/series
Labels: security, backport-PR

#2452 openssl updates (r151030)
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2021-3712.patch
  build/openssl/patches-1.0/series
Labels: security, backport-PR

#2461 fix p7zip truncates password to 8 chars (r151030)
  build/p7zip/patches/getpassphrase.patch
  build/p7zip/patches/series
Labels: backport-PR

#2460 fix p7zip truncates password to 8 chars (r151036)
  build/p7zip/patches/getpassphrase.patch
  build/p7zip/patches/series
Labels: backport-PR

#2459 fix p7zip truncates password to 8 chars (r151038)
  build/p7zip/build.sh
  build/p7zip/patches/getpassphrase.patch
  build/p7zip/patches/series
  build/p7zip/testsuite.log
Labels: backport-PR

#2458 fix p7zip truncates password to 8 chars
  build/p7zip/patches/gcc11.patch
  build/p7zip/patches/getpassphrase.patch
  build/p7zip/patches/series
  build/p7zip/testsuite.log
Labels: backport-todo
