Repository omniosorg/omnios-build, pull requests merged in 2021-01, with the labels that each got.

#2149 package updates
  build/cpuid/build.sh
  build/entire/entire.pkg
  build/git/build.sh
  build/git/testsuite.log
  build/jeos/omnios-userland.pkg
  build/wget/build.sh
  build/wget/local.mog
  build/wget/patches/autoconf.patch
  build/wget/patches/gcc10.patch
  build/wget/patches/hostos.patch
  build/wget/patches/nofuzz.patch
  build/wget/patches/series
  build/wget/testsuite.log
  doc/packages.md
Labels: package update

#2150 package updates
  build/jeos/omnios-userland.pkg
  build/libpcap/build.sh
  build/libpcap/local.mog
  build/mozilla-nss-nspr/build.sh
  build/socat/build.sh
  build/socat/patches/getprotobynumber_r_compat.patch
  build/socat/patches/multiple_symbols.patch
  build/socat/patches/series
  doc/packages.md
Labels: backport-todo, package update

#2152 socat: update to 1.7.4.0 (r151034)
  build/socat/build.sh
  build/socat/patches/getprotobynumber_r_compat.patch
  build/socat/patches/series
Labels: backport-PR, package update

#2151 socat: update to 1.7.4.0 (r151036)
  build/socat/build.sh
  build/socat/patches/getprotobynumber_r_compat.patch
  build/socat/patches/multiple_symbols.patch
  build/socat/patches/series
Labels: backport-PR, package update

#2155 socat: update to 1.7.4.1 (r151036)
  build/socat/build.sh
Labels: backport-PR, package update

#2156 socat: update to 1.7.4.1 (r151034)
  build/socat/build.sh
Labels: backport-PR, package update

#2154 package updates
  build/entire/entire.pkg
  build/findutils/build.sh
  build/findutils/testsuite.log
  build/gtar/build.sh
  build/gtar/patches/progname.patch
  build/gtar/patches/revert_check_return_value_from_xgetcwd.patch
  build/gtar/patches/series
  build/gtar/patches/sys-limits.patch
  build/gtar/testsuite.log
  build/jeos/omnios-userland.pkg
  build/python39/cryptography/build.sh
  build/python39/idna/build.sh
  build/python39/idna/local.mog
  build/python39/jaraco/build.sh
  build/python39/meson/build.sh
  build/python39/setuptools/build.sh
  build/socat/build.sh
  build/wget/build.sh
  doc/packages.md
Labels: package update

#2161 sudo: update to 1.9.5p1
  build/sudo/build.sh
  doc/packages.md
Labels: package update

#2166 OpenJDK11 needs to bundle core fonts (r151036)
  build/openjdk11/build.sh
  build/openjdk11/local.mog
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/series
  build/openjdk11/test/Fonts.java
Labels: backport-PR

#2165 OpenJDK11 needs to bundle core fonts
  build/openjdk11/build.sh
  build/openjdk11/local.mog
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/series
  build/openjdk11/test/Fonts.java
Labels: backport-todo

#2164 package updates
  build/open-vm-tools/build.sh
  build/python39/meson/build.sh
  doc/packages.md
Labels: package update

#2173 openjdk updates
  build/openjdk11/build.sh
  build/openjdk11/patches/illumos-cpu_microcode_revision.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/patch-make_autoconf_spec.gmk.in
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/series
  build/openjdk8/build.sh
  build/openjdk8/files/ctf.ignore
  build/openjdk8/files/ctf.skip
  build/openjdk8/local.mog
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/illumos-port-6.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_gcc.make.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/series
  doc/packages.md
Labels: backport-todo, package update

#2172 openjdk updates (r151036)
  build/openjdk11/build.sh
  build/openjdk11/patches/illumos-cpu_microcode_revision.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/patch-make_autoconf_spec.gmk.in
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/series
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/illumos-port-6.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_gcc.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__saproc.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_CreateJars.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_net__util__md.c.patch
  build/openjdk8/patches/patch-jdk_test_java_lang_management_OperatingSystemMXBean_GetSystemLoadAverage.java.patch
  build/openjdk8/patches/patch-jdk_test_sun_security_ec_TestEC.java.patch
  build/openjdk8/patches/series
Labels: backport-PR

#2171 openjdk8: update to 1.8.282-b08 (r151034)
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/illumos-port-6.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_gcc.make.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__saproc.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_CreateJars.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_net__util__md.c.patch
  build/openjdk8/patches/patch-jdk_test_java_lang_management_OperatingSystemMXBean_GetSystemLoadAverage.java.patch
  build/openjdk8/patches/patch-jdk_test_sun_security_ec_TestEC.java.patch
  build/openjdk8/patches/series
Labels: backport-PR

#2170 openjdk8: update to 1.8.282-b08 (r151030)
  build/openjdk8/build.sh
  build/openjdk8/patches/KPIC.patch
  build/openjdk8/patches/illumos-port-6.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch
  build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_gcc.make.patch
  build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch
  build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch
  build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch
  build/openjdk8/patches/patch-jdk_make_CreateJars.gmk.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_net__util__md.c.patch
  build/openjdk8/patches/patch-jdk_test_java_lang_management_OperatingSystemMXBean_GetSystemLoadAverage.java.patch
  build/openjdk8/patches/patch-jdk_test_sun_security_ec_TestEC.java.patch
  build/openjdk8/patches/series
Labels: backport-PR

#2176 Package updates (core)
  build/bind/build.sh
  build/sqlite3/build.sh
  doc/packages.md
Labels: package update

#2177 perl: update to 5.32.1
  build/perl/build.sh
  build/perl/local.mog
  build/perl/testsuite.log
  doc/packages.md
  lib/mog/global-transforms.mog
Labels: package update

#2178 package updates
  build/binutils/build.sh
  build/bison/build.sh
  build/bison/testsuite.log
  doc/packages.md
Labels: package update

#2182 sudo: update to 1.9.5p2 (r151036)
  build/sudo/build.sh
  doc/ReleaseNotes.md
Labels: backport-PR, package update

#2184 sudo: update to 1.9.5p2 (r151030)
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/sudo/build.sh
  build/sudo/patches/CVE-2019-18634.patch
  build/sudo/patches/series
  doc/ReleaseNotes.md
Labels: backport-PR, package update

#2183 sudo: update to 1.9.5p2 (r151034)
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/sudo/build.sh
  doc/ReleaseNotes.md
Labels: backport-PR, package update

#2181 sudo: update to 1.9.5p2
  build/sudo/build.sh
  doc/packages.md
Labels: backport-todo, package update

#2185 nss: update to 3.61
  build/mozilla-nss-nspr/build.sh
  doc/packages.md
Labels: package update
