Repository omniosorg/omnios-build, pull requests merged in 2021-05, with the labels that each got.

#2364 libxml2: update to 2.9.12 (r151030)
  build/libxml2/build.sh
  build/libxml2/patches/pthread.patch
Labels: backport-PR, package update

#2365 libxml2: update to 2.9.12 (r151036)
  build/libxml2/build.sh
  build/libxml2/patches/pthread.patch
Labels: backport-PR, package update

#2366 libxml2: update to 2.9.12 (r151038)
  build/libxml2/build.sh
  build/libxml2/patches/pthread.patch
Labels: backport-PR, package update

#2375 Core package updates
  build/bind/build.sh
  build/expat/build.sh
  build/libedit/build.sh
  build/sigcpp/build.sh
  doc/packages.md
  doc/rtime
Labels: package update

#2374 welcome perl 5.34
  build/perl/build.sh
  build/perl/testsuite.log
  doc/packages.md
Labels: package update

#2378 Python module updates
  build/python39/more-itertools/build.sh
  build/python39/pip/build.sh
  build/python39/setuptools/build.sh
  doc/packages.md
  lib/functions.sh
Labels: package update

#2379 curl - update from 7.76.1 to 7.77.0
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: backport-todo, package update

#2380 curl - update from 7.76.1 to 7.77.0 (r151038)
  build/curl/build.sh
Labels: backport-PR, package update

#2381 curl - update from 7.76.1 to 7.77.0 (r151036)
  build/curl/build.sh
Labels: backport-PR, package update

#2382 curl - update from 7.76.1 to 7.77.0 (r151030)
  build/curl/build.sh
  build/curl/patches/series
  build/curl/patches/ssl23.patch
Labels: backport-PR, package update
