Repository omniosorg/omnios-build, pull requests merged in 2022-05, with the labels that each got.

#2787 curl - update from 7.82.0 to 7.83.0 (r151042)
  build/curl/build.sh
  build/curl/patches/openssl-cn-bug.patch
  build/curl/patches/series
Labels: package update, backport-PR

#2786 curl - update from 7.79.1 to 7.83.0 (r151038)
  build/curl/build.sh
Labels: package update, backport-PR

#2788 curl - update from 7.79.1 to 7.83.0 (r151040)
  build/curl/build.sh
Labels: package update, backport-PR

#2789 curl - update from 7.79.1 to 7.83.0 (r151030)
  build/curl/build.sh
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2794 openssl updates (r151030)
  build/openssl/build.sh
  build/openssl/patches-1.0/CVE-2022-1292.patch
  build/openssl/patches-1.0/series
Labels: package update, security, backport-PR

#2793 openssl updates (r151038)
  build/openssl/build-1.1.sh
  build/openssl/patches-1.0/CVE-2022-1292.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite-1.1.log
Labels: package update, security, backport-PR

#2792 openssl updates (r151040)
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-1.0/CVE-2022-1292.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite-1.1.log
  build/openssl/testsuite-3.log
Labels: package update, security, backport-PR

#2791 openssl updates (r151042)
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-1.0/CVE-2022-1292.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite-1.1.log
  build/openssl/testsuite-3.log
Labels: package update, security, backport-PR

#2790 openssl updates
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-1.0/CVE-2022-1292.patch
  build/openssl/patches-1.0/series
  build/openssl/testsuite-1.1.log
  build/openssl/testsuite-3.log
  doc/packages.md
Labels: package update, backport-todo, security

#2808 Core package updates
  build/git/build.sh
  build/mercurial/build.sh
  build/python310/cryptography/build.sh
  build/python310/jsonschema/build.sh
  build/python310/meson/build.sh
  build/python310/more-itertools/build.sh
  build/python310/orjson/build.sh
  build/python310/prettytable/build.sh
  build/python310/setuptools-rust/build.sh
  build/python310/setuptools/build.sh
  build/python310/typing-extensions/build.sh
  build/rsyslog/build.sh
  build/rsyslog/testsuite.log
  build/sqlite3/build.sh
  build/unixodbc/build.sh
  build/unixodbc/patches/filterlibs.patch
  doc/packages.md
Labels: package update

#2803 libxml2 - update from 2.9.13 to 2.9.14
  build/libxml2/build.sh
  build/libxml2/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2805 libxml2 - update from 2.9.13 to 2.9.14 (r151042)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2804 libxml2 - update from 2.9.13 to 2.9.14 (r151040)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2806 libxml2 - update from 2.9.13 to 2.9.14 (r151038)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2810 curl - update from 7.83.0 to 7.83.1
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2812 curl - update from 7.83.0 to 7.83.1 (r151038)
  build/curl/build.sh
Labels: package update, backport-PR

#2811 curl - update from 7.83.0 to 7.83.1 (r151040)
  build/curl/build.sh
Labels: package update, backport-PR

#2813 curl - update from 7.83.0 to 7.83.1 (r151042)
  build/curl/build.sh
Labels: package update, backport-PR

#2817 tcsh - update from 6.24.00 to 6.24.01
  build/tcsh/build.sh
  build/tcsh/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2818 tcsh - update from 6.24.00 to 6.24.01 (r151042)
  build/tcsh/build.sh
Labels: package update, backport-PR

#2820 python39 - update from 3.9.12 to 3.9.13 (r151040)
  build/python39/build.sh
  build/python39/patches/enable-ossaudiodev.patch
  build/python39/patches/mod-posix-sched_priority.patch
  build/python39/patches/revert-makedirs.patch
Labels: package update

#2819 python39 - update from 3.9.12 to 3.9.13 (r151038)
  build/python39/build.sh
  build/python39/patches/enable-ossaudiodev.patch
  build/python39/patches/mod-posix-sched_priority.patch
  build/python39/patches/revert-makedirs.patch
Labels: package update

#2821 bind: update to 9.18.3
  build/bind/build.sh
  build/bind/local.mog
  build/bind/patches/libs.patch
  build/bind/patches/linker_flags.patch
  build/bind/patches/series
  doc/packages.md
Labels: package update
