Repository omniosorg/omnios-build, pull requests merged in 2022-01, with the labels that each got.

#2639 package updates
  build/bind/build.sh
  build/expat/build.sh
  build/python310/attrs/build.sh
  build/python310/coverage/build.sh
  build/python310/cryptography/build.sh
  build/python310/jaraco/build.sh
  build/python310/jsonschema/build.sh
  build/python310/meson/build.sh
  build/python310/orjson/build.sh
  build/python310/prettytable/build.sh
  build/python310/setuptools-rust/build.sh
  build/python310/setuptools/build.sh
  build/python310/tomli/build.sh
  build/python310/typing-extensions/build.sh
  build/sqlite3/build.sh
  doc/packages.md
Labels: package update

#2646 expat - update from 2.4.2 to 2.4.3
  build/expat/build.sh
  doc/packages.md
Labels: package update, backport-todo

#2647 expat - update from 2.4.1 to 2.4.3 (r151040)
  build/expat/build.sh
  build/expat/patches/manpage.patch
  build/expat/patches/no_link_libm.patch
  build/expat/patches/series
Labels: package update, backport-PR

#2649 expat - update from 2.2.8 to 2.4.3 (r151030)
  build/entire/entire.pkg
  build/expat/build.sh
  build/expat/patches/manpage.patch
  build/expat/patches/no_link_libm.patch
  build/expat/patches/series
  build/jeos/omnios-userland.pkg
Labels: package update, backport-PR

#2648 expat - update from 2.3.0 to 2.4.3 (r151038)
  build/expat/build.sh
  build/expat/patches/manpage.patch
  build/expat/patches/no_link_libm.patch
  build/expat/patches/series
Labels: package update, backport-PR

#2655 OpenJDK updates
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk17/build.sh
  build/openjdk17/patches/disable-ld-check.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/series
  doc/packages.md
Labels: package update

#2658 bind - update from 9.16.24 to 9.16.25
  build/bind/build.sh
  build/bind/patches/linker_flags.patch
  doc/packages.md
Labels: package update

#2659 openjdk updates (r151040)
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk17/build.sh
  build/openjdk17/patches/disable-ld-check.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/series
Labels: backport-PR

#2660 openjdk11: update to 11.0.14+9 (r151038)
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
Labels: backport-PR

#2663 git - update from 2.35.0 to 2.35.1
  build/git/build.sh
  doc/packages.md
Labels: package update

#2666 expat - update from 2.4.3 to 2.4.4
  build/expat/build.sh
  build/expat/patches/manpage.patch
  doc/packages.md
Labels: package update, backport-todo, security

#2667 expat - update from 2.4.3 to 2.4.4 (r151040)
  build/expat/build.sh
Labels: package update, backport-PR

#2669 expat - update from 2.4.3 to 2.4.4 (r151030)
  build/expat/build.sh
Labels: package update, backport-PR
