Repository omniosorg/omnios-build, pull requests merged in 2022-12, with the labels that each got.

#3018 Core package updates
  build/glib/build.sh
  build/glib/testsuite.log
  build/open-vm-tools/build.sh
  build/pciutils/build.sh
  build/pciutils/patches/Revert-Library-Handle-domains-in-all-back-ends.patch
  build/pcre2/build.sh
  build/pcre2/testsuite.log
  build/python310/build.sh
  build/python310/patches/disable_epoll.patch
  build/python310/patches/mod-posix-sched_priority.patch
  build/python310/patches/test-shutil.patch
  build/python310/testsuite.log
  build/python311/build.sh
  build/python311/patches/disable_epoll.patch
  build/python311/patches/mod-posix-sched_priority.patch
  build/python311/patches/no-zip-in-sys-path.patch
  build/python311/patches/series
  build/python311/testsuite.log
  build/rsyslog/build.sh
  build/rsyslog/testsuite.log
  build/swig/build.sh
  build/swig/testsuite.log
  build/tcsh/build.sh
  build/tcsh/patches/test.patch
  build/tcsh/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3026 python310 - update from 3.10.8 to 3.10.9 (r151042)
  build/python310/build.sh
  build/python310/patches/disable_epoll.patch
  build/python310/patches/mod-posix-sched_priority.patch
  build/python310/patches/test-shutil.patch
  build/python310/testsuite.log
Labels: backport-PR

#3025 python310 - update from 3.10.8 to 3.10.9 (r151044)
  build/python310/build.sh
  build/python310/patches/disable_epoll.patch
  build/python310/patches/mod-posix-sched_priority.patch
  build/python310/patches/test-shutil.patch
  build/python310/testsuite.log
Labels: backport-PR

#3036 curl - update from 7.86.0 to 7.87.0 (r151042)
  build/curl/build.sh
Labels: package update, backport-PR

#3035 curl - update from 7.86.0 to 7.87.0 (r151044)
  build/curl/build.sh
Labels: package update, backport-PR

#3034 curl - update from 7.86.0 to 7.87.0
  build/curl/build.sh
  doc/packages.md
Labels: package update, backport-todo

#3037 curl - update from 7.86.0 to 7.87.0 (r151038)
  build/curl/build.sh
Labels: package update, backport-PR
