Repository omniosorg/omnios-build, pull requests merged in 2022-07, with the labels that each got.

#2852 Core package updates
  build/git/build.sh
  build/git/testsuite.log
  build/glib/build.sh
  build/libidn/build.sh
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  build/python310/cffi/build.sh
  build/python310/jsonschema/build.sh
  build/python310/meson/build.sh
  build/python310/meson/patches/compiler_def_static_linker.patch
  build/python310/orjson/build.sh
  build/python310/typing-extensions/build.sh
  build/sqlite3/build.sh
  build/sudo/build.sh
  doc/packages.md
Labels: package update, backport-todo

#2857 openssl: update to 1.1.1q/3.0.5 (r151042)
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-3/GSD-2022-1002526.patch
  build/openssl/patches-3/series
Labels: package update, backport-PR

#2856 openssl: update to 1.1.1q/3.0.5 (r151040)
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-3/GSD-2022-1002526.patch
  build/openssl/patches-3/series
Labels: package update, backport-PR

#2854 openssl: update to 3.0.5/1.1.1q
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-3/GSD-2022-1002526.patch
  build/openssl/patches-3/series
  build/openssl/testsuite-1.1.log
  build/openssl/testsuite-3.log
  doc/packages.md
Labels: package update, backport-todo

#2855 openssl: update to 1.1.1q (r151038)
  build/openssl/build-1.1.sh
Labels: package update, backport-PR

#2860 Python module updates
  build/python310/cryptography/build.sh
  build/python310/jsonschema/build.sh
  build/python310/meson/build.sh
  build/python310/meson/patches/compiler_def_static_linker.patch
  build/python310/orjson/build.sh
  build/python310/rapidjson/build.sh
  build/python310/setuptools-rust/build.sh
  build/python310/setuptools/build.sh
  doc/packages.md
Labels: package update

#2859 cloud-init - update from 22.2 to 22.2.2
  build/cloud-init/build.sh
  doc/packages.md
Labels: package update

#2867 openjdk11: update to 11.0.16+8 (r151038)
  build/openjdk11/build.sh
Labels: backport-PR

#2866 openjdk updates (r151040)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk17/patches/series
Labels: backport-PR

#2865 openjdk updates
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk17/patches/series
  doc/packages.md
Labels: package update, backport-todo

#2864 openjdk updates (r151042)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk17/patches/series
Labels: backport-PR

#2869 Core package updates
  build/bind/build.sh
  build/git/build.sh
  build/mercurial/build.sh
  build/mozilla-nss-nspr/build.sh
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/series
  build/python310/coverage/build.sh
  build/python310/jsonschema/build.sh
  build/python310/orjson/build.sh
  build/python310/pip/build.sh
  build/python310/pip/patches/protect-vendor-packages.patch
  build/python310/pip/patches/system-certificates.patch
  build/python310/setuptools/build.sh
  build/sqlite3/build.sh
  doc/packages.md
Labels: package update

#2870 openjdk8 - update from 1.8.332-09 to 1.8.342-07 (r151038)
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2871 openjdk8 - update from 1.8.332-09 to 1.8.342-07 (r151040)
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2872 openjdk8 - update from 1.8.332-09 to 1.8.342-07 (r151042)
  build/openjdk8/build.sh
  build/openjdk8/create_jdk_bundle.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-jdk_make_Images.gmk.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2873 iso-codes - update from 4.10.0 to 4.11.0
  build/iso-codes/build.sh
  doc/packages.md
Labels: package update

#2877 net-snmp - update from 5.9.1 to 5.9.3 (r151040)
  build/net-snmp/build.sh
  build/net-snmp/patches/010.if-mib-zone.patch
  build/net-snmp/patches/011.Makefile.in.patch
  build/net-snmp/patches/029.7097655.ipAddressTable_container.patch
  build/net-snmp/patches/038.16032482.kernel_sunos5.patch
  build/net-snmp/patches/043.16634190.kernel_sunos5.patch
  build/net-snmp/patches/060.20461627.17502158.kernel_sunos5.patch
  build/net-snmp/patches/068.configure.patch
  build/net-snmp/patches/closefrom.patch
  build/net-snmp/patches/series
  build/net-snmp/patches/testsuite.patch
  build/net-snmp/testsuite.log
Labels: package update, backport-PR

#2878 net-snmp - update from 5.9 to 5.9.3 (r151038)
  build/net-snmp/build.sh
  build/net-snmp/patches-5.8/002.pkcs.patch
  build/net-snmp/patches-5.8/008.ip-mib.patch
  build/net-snmp/patches-5.8/009.ltmain.sh.patch
  build/net-snmp/patches-5.8/010.if-mib-zone.patch
  build/net-snmp/patches-5.8/011.Makefile.in.patch
  build/net-snmp/patches-5.8/012.Makefile.PL.patch
  build/net-snmp/patches-5.8/014.6801093.vmstat_solaris2.patch
  build/net-snmp/patches-5.8/015.6956251.vmstat_solaris2.patch
  build/net-snmp/patches-5.8/016.6934478.vmstat_solaris2.patch
  build/net-snmp/patches-5.8/020.7018550.kernel_sunos5.patch
  build/net-snmp/patches-5.8/021.7027183.kernel_sunos5.patch
  build/net-snmp/patches-5.8/024.7119673,7127371.kernel_sunos5.patch
  build/net-snmp/patches-5.8/027.7118090.hr_filesys.patch
  build/net-snmp/patches-5.8/028.7069199.doxygen.conf.patch
  build/net-snmp/patches-5.8/029.7097655.ipAddressTable_container.patch
  build/net-snmp/patches-5.8/030.7147779.kernel_sunos5.patch
  build/net-snmp/patches-5.8/038.16032482.kernel_sunos5.patch
  build/net-snmp/patches-5.8/039.17002960.kernel_sunos5.patch
  build/net-snmp/patches-5.8/043.16634190.kernel_sunos5.patch
  build/net-snmp/patches-5.8/048.16439911.hr_filesys.patch
  build/net-snmp/patches-5.8/053.20191950.dladm_proto_change.patch
  build/net-snmp/patches-5.8/054.20479968.net-snmp-config.in.patch
  build/net-snmp/patches-5.8/058.15372155.hr_storage.patch
  build/net-snmp/patches-5.8/060.20461627.17502158.kernel_sunos5.patch
  build/net-snmp/patches-5.8/067.1.kernel_sunos5.patch
  build/net-snmp/patches-5.8/068.configure.patch
  build/net-snmp/patches/010.if-mib-zone.patch
  build/net-snmp/patches/011.Makefile.in.patch
  build/net-snmp/patches/024.7119673,7127371.kernel_sunos5.patch
  build/net-snmp/patches/029.7097655.ipAddressTable_container.patch
  build/net-snmp/patches/030.7147779.kernel_sunos5.patch
  build/net-snmp/patches/038.16032482.kernel_sunos5.patch
  build/net-snmp/patches/039.17002960.kernel_sunos5.patch
  build/net-snmp/patches/043.16634190.kernel_sunos5.patch
  build/net-snmp/patches/053.20191950.dladm_proto_change.patch
  build/net-snmp/patches/054.20479968.net-snmp-config.in.patch
  build/net-snmp/patches/060.20461627.17502158.kernel_sunos5.patch
  build/net-snmp/patches/068.configure.patch
  build/net-snmp/patches/closefrom.patch
  build/net-snmp/patches/series
  build/net-snmp/patches/testsuite.patch
  build/net-snmp/testsuite.log
Labels: package update, backport-PR

#2876 net-snmp - update from 5.9.1 to 5.9.3 (r151042)
  build/net-snmp/build.sh
  build/net-snmp/patches/010.if-mib-zone.patch
  build/net-snmp/patches/011.Makefile.in.patch
  build/net-snmp/patches/029.7097655.ipAddressTable_container.patch
  build/net-snmp/patches/038.16032482.kernel_sunos5.patch
  build/net-snmp/patches/043.16634190.kernel_sunos5.patch
  build/net-snmp/patches/060.20461627.17502158.kernel_sunos5.patch
  build/net-snmp/patches/068.configure.patch
  build/net-snmp/patches/closefrom.patch
  build/net-snmp/patches/series
  build/net-snmp/patches/testsuite.patch
  build/net-snmp/testsuite.log
Labels: package update, backport-PR

#2875 net-snmp - update from 5.9.1 to 5.9.3
  build/net-snmp/build.sh
  build/net-snmp/patches/010.if-mib-zone.patch
  build/net-snmp/patches/011.Makefile.in.patch
  build/net-snmp/patches/029.7097655.ipAddressTable_container.patch
  build/net-snmp/patches/038.16032482.kernel_sunos5.patch
  build/net-snmp/patches/043.16634190.kernel_sunos5.patch
  build/net-snmp/patches/060.20461627.17502158.kernel_sunos5.patch
  build/net-snmp/patches/068.configure.patch
  build/net-snmp/patches/closefrom.patch
  build/net-snmp/patches/series
  build/net-snmp/patches/testsuite.patch
  build/net-snmp/testsuite.log
  doc/packages.md
Labels: package update
