Repository omniosorg/omnios-build, pull requests merged in 2022-10, with the labels that each got.

#2949 zlib - update from 1.2.12 to 1.2.13
  build/grep/patches/disable-egrep-fgrep-warnings.patch
  build/grep/patches/series
  build/zlib/build.sh
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
  build/zlib/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2952 zlib - update from 1.2.12 to 1.2.13 (r151038)
  build/zlib/build.sh
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
  build/zlib/testsuite.log
Labels: package update, backport-PR

#2950 zlib - update from 1.2.12 to 1.2.13 (r151044)
  build/grep/patches/disable-egrep-fgrep-warnings.patch
  build/grep/patches/series
  build/zlib/build.sh
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
  build/zlib/testsuite.log
Labels: package update, backport-PR

#2959 python310 - update from 3.10.7 to 3.10.8 (r151044)
  build/python310/build.sh
Labels: package update, backport-PR

#2960 python39 - update from 3.9.14 to 3.9.15 (r151040)
  build/python39/build.sh
  build/python39/patches/mod-posix-sched_priority.patch
Labels: package update, backport-PR

#2962 python39 - update from 3.9.14 to 3.9.15 (r151038)
  build/python39/build.sh
  build/python39/patches/mod-posix-sched_priority.patch
  build/python39/patches/module-py_db.patch
Labels: package update, backport-PR

#2961 python310 - update from 3.10.7 to 3.10.8 (r151042)
  build/python310/build.sh
Labels: package update, backport-PR

#2963 Core package updates
  build/libxml2/build.sh
  build/python310/build.sh
  doc/packages.md
Labels: package update, backport-todo

#2958 libxml2 - update from 2.10.1 to 2.10.3 (r151038)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2956 libxml2 - update from 2.10.1 to 2.10.3 (r151040)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2955 libxml2 - update from 2.10.1 to 2.10.3 (r151042)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2957 libxml2 - update from 2.10.2 to 2.10.3 (r151044)
  build/libxml2/build.sh
Labels: package update, backport-PR

#2974 openjdk updates (r151044)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/memcntl-remove-own-declaration.patch
  build/openjdk17/patches/series
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2972 openjdk updates (r151040)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2971 openjdk updates (r151038)
  build/openjdk11/build.sh
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2970 openjdk updates
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/memcntl-remove-own-declaration.patch
  build/openjdk17/patches/series
  build/openjdk8/build.sh
  doc/packages.md
  lib/config.sh
  lib/functions.sh
Labels: package update

#2973 openjdk updates (r151042)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/memcntl-remove-own-declaration.patch
  build/openjdk17/patches/series
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2977 zstd: fix 64-bit libzstd.pc (r151042)
  build/zstd/build.sh
Labels: backport-PR

#2978 zstd: fix 64-bit libzstd.pc (r151038)
  build/zstd/build.sh
Labels: backport-PR

#2979 zstd: fix 64-bit libzstd.pc (r151040)
  build/zstd/build.sh
Labels: backport-PR

#2976 zstd: fix 64-bit libzstd.pc
  build/zstd/build.sh
Labels: backport-todo

#2975 zstd: fix 64-bit libzstd.pc (r151044)
  build/zstd/build.sh
Labels: backport-PR

#2985 curl - update from 7.84.0 to 7.86.0 (r151040)
  build/curl/build.sh
  build/curl/patches/tests.patch
Labels: package update, backport-PR

#2987 curl - update from 7.84.0 to 7.86.0 (r151038)
  build/curl/build.sh
  build/curl/patches/tests.patch
Labels: package update, backport-PR

#2988 curl - update from 7.84.0 to 7.86.0 (r151042)
  build/curl/build.sh
  build/curl/patches/tests.patch
Labels: package update, backport-PR

#2989 curl - update from 7.85.0 to 7.86.0
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2986 curl - update from 7.85.0 to 7.86.0 (r151044)
  build/curl/build.sh
Labels: package update, backport-PR
