Repository omniosorg/omnios-build, pull requests merged in 2022-04, with the labels that each got.

#2737 gzip: update from 1.11 to 1.12
  build/gzip/build.sh
  build/gzip/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2738 gzip - update from 1.11 to 1.12 (r151040)
  build/gzip/build.sh
Labels: package update, backport-PR

#2739 gzip - update from 1.11 to 1.12 (r151042)
  build/gzip/build.sh
Labels: package update, backport-PR

#2740 gzip - update from 1.10 to 1.12 (r151038)
  build/gzip/build.sh
Labels: package update, backport-PR

#2741 gzip - update from 1.10 to 1.12 (r151030)
  build/entire/entire.pkg
  build/gzip/build.sh
  build/jeos/omnios-userland.pkg
Labels: package update, backport-PR

#2749 zlib - update from 1.2.11 to 1.2.12 (r151030)
  build/entire/entire.pkg
  build/jeos/omnios-userland.pkg
  build/zlib/build.sh
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
  build/zlib/testsuite.log
Labels: package update, backport-PR

#2747 zlib - update from 1.2.11 to 1.2.12 (r151038)
  build/zlib/build.sh
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
  build/zlib/testsuite.log
Labels: package update, backport-PR

#2745 zlib - update from 1.2.11 to 1.2.12 (r151040)
  build/zlib/build.sh
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
  build/zlib/testsuite.log
Labels: package update, backport-PR

#2744 zlib: Correct incorrect inputs provided to the CRC functions (r151042)
  build/zlib/patches/crc32_input.patch
  build/zlib/patches/series
Labels: backport-PR

#2752 vim: update to 8.2.4691 (r151042)
  build/vim/build.sh
Labels: package update, backport-PR

#2753 vim: update to 8.2.4691 (r151040)
  build/vim/build.sh
Labels: package update, backport-PR

#2757 git - update from 2.31.1 to 2.31.2 (r151038)
  build/git/build.sh
Labels: package update, backport-PR

#2755 git - update from 2.35.1 to 2.35.2 (r151042)
  build/git/build.sh
Labels: package update, backport-PR

#2756 git - update from 2.33.1 to 2.33.2 (r151040)
  build/git/build.sh
Labels: package update, backport-PR

#2761 openjdk updates (r151038)
  build/openjdk11/build.sh
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2760 openjdk updates (r151040)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2763 openjdk updates
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  doc/packages.md
Labels: package update, backport-todo

#2759 openjdk updates (r151042)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
Labels: package update, backport-PR

#2769 Move CA certificates back to /etc/ssl/certs/ (r151042)
  build/ca-bundle/build.sh
Labels: backport-PR

#2775 openjdk8: update to 1.8.332-09 (r151038)
  build/openjdk8/build.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2774 openjdk8: update to 1.8.332-09 (r151040)
  build/openjdk8/build.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2773 openjdk8: update to 1.8.332-09
  build/openjdk8/build.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
  doc/packages.md
Labels: package update, backport-todo

#2772 openjdk8: update to 1.8.332-09 (r151042)
  build/openjdk8/build.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2762 openjdk8: update to 1.8.332-09 (r151030)
  build/openjdk8/build.sh
  build/openjdk8/patches/build-non-scm.patch
  build/openjdk8/patches/ldflags-pie.patch
  build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch
  build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch
  build/openjdk8/patches/series
Labels: package update, backport-PR

#2783 fix openjdk11/17 builds following integration of illumos 14418
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk17/patches/memcntl-remove-own-declaration.patch
  build/openjdk17/patches/series
Labels: backport-todo

#2784 fix openjdk11/17 builds following integration of illumos 14418 (r151042)
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk17/patches/memcntl-remove-own-declaration.patch
  build/openjdk17/patches/series
Labels: backport-PR
