Repository omniosorg/omnios-build, pull requests merged in 2022-08, with the labels that each got.

#2880 python310 - update from 3.10.5 to 3.10.6
  build/python310/build.sh
  build/python310/patches/enable-ossaudiodev.patch
  build/python310/patches/mod-socket-xpg6.patch
  build/python310/patches/module-dlpi.patch
  build/python310/patches/module-priv-rbac.patch
  build/python310/patches/module-ucred.patch
  build/python310/patches/setup.patch
  build/python310/patches/test-shutil.patch
  doc/packages.md
Labels: package update, backport-todo

#2881 python310 - update from 3.10.5 to 3.10.6 (r151042)
  build/python310/build.sh
  build/python310/patches/enable-ossaudiodev.patch
  build/python310/patches/mod-socket-xpg6.patch
  build/python310/patches/module-dlpi.patch
  build/python310/patches/module-priv-rbac.patch
  build/python310/patches/module-ucred.patch
  build/python310/patches/setup.patch
  build/python310/patches/test-shutil.patch
Labels: package update, backport-PR

#2882 openjdk8: update from 1.8.342-07 -> 1.8.345-01
  build/openjdk8/build.sh
  doc/packages.md
Labels: package update, backport-todo

#2883 openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151042)
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2884 openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151040)
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2885 openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151038)
  build/openjdk8/build.sh
Labels: package update, backport-PR

#2888 binutils - update from 2.38 to 2.39
  build/binutils/build.sh
  build/binutils/patches/startstop.patch
  doc/packages.md
Labels: package update

#2895 Add runtime/java/runtime64 package (r151042)
  build/obsolete/runtime-java-runtime64.p5m
  build/obsolete/runtime-java.p5m
  doc/baseline
Labels: backport-PR

#2896 Add runtime/java/runtime64 package (r151040)
  build/obsolete/runtime-java-runtime64.p5m
  build/obsolete/runtime-java.p5m
  doc/baseline
Labels: backport-PR

#2897 Add runtime/java/runtime64 package (r151038)
  build/obsolete/runtime-java-runtime64.p5m
  build/obsolete/runtime-java.p5m
  doc/baseline
Labels: backport-PR

#2898 zsh: update to 5.9
  build/zsh/build.sh
  build/zsh/patches/fix_shebang.patch
  build/zsh/patches/no-posix.patch
  build/zsh/patches/series
  build/zsh/patches/shared.patch
  build/zsh/patches/testsuite.patch
  build/zsh/testsuite.log
  doc/packages.md
Labels: package update

#2899 Core package updates
  build/bind/build.sh
  build/git/build.sh
  build/git/testsuite.log
  build/libxml2/build.sh
  build/libxml2/local.mog
  build/libxml2/patches/pthread.patch
  build/libxml2/testsuite.log
  build/lz4/build.sh
  build/lz4/testsuite.log
  build/mozilla-nss-nspr/build.sh
  build/python310/coverage/build.sh
  build/python310/jsonschema/build.sh
  build/python310/meson/build.sh
  build/python310/meson/patches/compiler_def_static_linker.patch
  build/python310/meson/patches/thin-libraries-breakage.patch
  build/python310/orjson/build.sh
  build/python310/setuptools-rust/build.sh
  build/python310/setuptools/build.sh
  build/rsync/build.sh
  build/xz/build.sh
  build/xz/local.mog
  build/xz/patches/pthread.diff
  build/xz/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#2902 Backports to r151040
  build/libxml2/build.sh
  build/libxml2/local.mog
  build/libxml2/patches/pthread.patch
  build/xz/build.sh
  build/xz/local.mog
  build/xz/patches/pthread.diff
  build/zlib/build.sh
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/series
Labels: package update, backport-PR

#2901 Backports to r151042
  build/libxml2/build.sh
  build/libxml2/local.mog
  build/libxml2/patches/pthread.patch
  build/xz/build.sh
  build/xz/local.mog
  build/xz/patches/pthread.diff
  build/zlib/build.sh
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/series
Labels: package update, backport-PR

#2900 zlib: fix for CVE-2022-37434
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/series
Labels: package update, backport-todo

#2903 Backports to r151038
  build/libxml2/build.sh
  build/libxml2/local.mog
  build/libxml2/patches/pthread.patch
  build/xz/build.sh
  build/xz/local.mog
  build/xz/patches/pthread.diff
  build/zlib/build.sh
  build/zlib/patches/CVE-2022-37434-1.patch
  build/zlib/patches/CVE-2022-37434-2.patch
  build/zlib/patches/series
Labels: package update, backport-PR

#2906 cloud-init - update from 22.2.2 to 22.3
  build/cloud-init/build.sh
  doc/packages.md
Labels: package update

#2913 Backports to r151042
  build/libxml2/build.sh
  build/open-vm-tools/build.sh
Labels: package update, backport-PR

#2914 Backports to r151040
  build/libxml2/build.sh
  build/open-vm-tools/build.sh
  build/open-vm-tools/local.mog
  build/open-vm-tools/patches/gnu-ld.patch
  build/open-vm-tools/patches/lock.patch
  build/open-vm-tools/patches/unneededlibs.patch
Labels: package update, backport-PR

#2915 Backports to r151038
  build/libxml2/build.sh
  build/open-vm-tools/build.sh
  build/open-vm-tools/local.mog
  build/open-vm-tools/patches/gnu-ld.patch
  build/open-vm-tools/patches/lock.patch
  build/open-vm-tools/patches/nicInfo.patch
  build/open-vm-tools/patches/plugindir.patch
  build/open-vm-tools/patches/unneededlibs.patch
Labels: package update, backport-PR
