Repository omniosorg/omnios-build, pull requests merged in 2023-08, with the labels that each got.

#3309 add openjdk 17 (r151038)
  build/meta/omnios-build-tools.p5m
  build/openjdk17/build.sh
  build/openjdk17/local.mog
  build/openjdk17/patches/README-removal.txt
  build/openjdk17/patches/README.txt
  build/openjdk17/patches/disable-ld-check.patch
  build/openjdk17/patches/fontpath.patch
  build/openjdk17/patches/headless_build_needs_x11.patch
  build/openjdk17/patches/illumos-cpu_microcode_revision.patch
  build/openjdk17/patches/illumos-port-1.patch
  build/openjdk17/patches/illumos-port-10.patch
  build/openjdk17/patches/illumos-port-11.patch
  build/openjdk17/patches/illumos-port-12.patch
  build/openjdk17/patches/illumos-port-13.patch
  build/openjdk17/patches/illumos-port-14.patch
  build/openjdk17/patches/illumos-port-2.patch
  build/openjdk17/patches/illumos-port-3.patch
  build/openjdk17/patches/illumos-port-4.patch
  build/openjdk17/patches/illumos-port-5.patch
  build/openjdk17/patches/illumos-port-6.patch
  build/openjdk17/patches/illumos-port-7.patch
  build/openjdk17/patches/illumos-port-8.patch
  build/openjdk17/patches/illumos-port-9.patch
  build/openjdk17/patches/illumos-signal-1.patch
  build/openjdk17/patches/illumos-signal-2.patch
  build/openjdk17/patches/illumos-signal-3.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/omnios-headless.patch
  build/openjdk17/patches/patch-make_GenerateLinkOptData.gmk
  build/openjdk17/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk17/patches/patch-make_autoconf_jdk-options.m4
  build/openjdk17/patches/patch-make_launcher_LauncherCommon.gmk
  build/openjdk17/patches/patch-make_lib_LibCommon.gmk
  build/openjdk17/patches/patch-src_hotspot_os__cpu_solaris__x86_atomic__solaris__x86.hpp
  build/openjdk17/patches/patch-src_hotspot_os__cpu_solaris__x86_bytes__solaris__x86.inline.hpp
  build/openjdk17/patches/patch-src_hotspot_os__cpu_solaris__x86_prefetch__solaris__x86.inline.hpp
  build/openjdk17/patches/patch-src_hotspot_share_gc_g1_g1Analytics.cpp
  build/openjdk17/patches/patch-src_java.desktop_share_native_libsplashscreen_libpng_pngpriv.h
  build/openjdk17/patches/security-pkcs11.patch
  build/openjdk17/patches/series
  build/openjdk17/patches/tribblix-attachListener_solaris.patch
  build/openjdk17/patches/tribblix-demangle1.patch
  build/openjdk17/patches/tribblix-demangle4.patch
  build/openjdk17/patches/tribblix-flags-cflags.patch
  build/openjdk17/patches/tribblix-flags-ldflags.patch
  build/openjdk17/patches/tribblix-flags-ldflags2.patch
  build/openjdk17/patches/tribblix-flags-ldflags3.patch
  build/openjdk17/patches/tribblix-wait.patch
  build/openjdk17/test/.gitignore
  build/openjdk17/test/Makefile
  build/openjdk17/test/Test.java
  doc/baseline
Labels: backport-PR

#3322 Core package updates
  build/binutils/build.sh
  build/binutils/patches/gold-fallocate.patch
  build/binutils/patches/ld64so.patch
  build/binutils/patches/startstop.patch
  build/binutils/patches/stdio-limit.diff
  build/libgmp/build.sh
  build/libgmp/patches/bmi.patch
  build/libgmp/patches/gmp-h.in
  build/libgmp/testsuite.log
  build/mercurial/build.sh
  build/nss/build.sh
  build/pv/build.sh
  build/pv/patches/header.in.patch
  build/pv/patches/series
  build/pv/patches/stddef.patch
  build/xz/build.sh
  build/xz/testsuite.log
  doc/packages.md
Labels: package update

#3321 chrony: bump bundled nettle to 3.9.1 (r151044)
  build/chrony/build.sh
Labels: package update, backport-PR

#3320 chrony: bump bundled nettle to 3.9.1 (r151046)
  build/chrony/build.sh
Labels: package update, backport-PR

#3319 chrony: bump bundled nettle to 3.9.1
  build/chrony/build.sh
  doc/packages.md
  tools/test
Labels: package update, backport-todo

#3324 Core package updates
  build/README.md
  build/chrony/build.sh
  build/chrony/patches/illumos.patch
  build/chrony/testsuite.log
  build/libxml2/build.sh
  build/unixodbc/build.sh
  build/unixodbc/patches/filterlibs.patch
  build/unixodbc/patches/mutex-exit.patch
  doc/packages.md
Labels: package update

#3325 openssh: update from 9.3p2 to 9.4p1
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/series
  build/openssh/patches/sk-dummy-openssl.patch
  doc/packages.md
Labels: package update

#3329 screen - update from 4.9.0 to 4.9.1
  build/screen/build.sh
  build/screen/patches/Makefile.in.patch
  build/screen/patches/ncurses.patch
  build/screen/patches/unneededlibs.patch
  doc/packages.md
Labels: package update, backport-todo

#3330 screen - update from 4.9.0 to 4.9.1 (r151046)
  build/screen/build.sh
  build/screen/patches/Makefile.in.patch
  build/screen/patches/ncurses.patch
  build/screen/patches/unneededlibs.patch
Labels: package update, backport-PR

#3331 screen - update from 4.9.0 to 4.9.1 (r151044)
  build/screen/build.sh
  build/screen/patches/Makefile.in.patch
  build/screen/patches/ncurses.patch
  build/screen/patches/unneededlibs.patch
Labels: package update, backport-PR

#3332 screen - update from 4.8.0 to 4.9.1 (r151038)
  build/screen/build.sh
  build/screen/patches/Makefile.in.patch
  build/screen/patches/ncurses.patch
  build/screen/patches/series
  build/screen/patches/unneededlibs.patch
Labels: package update, backport-PR

#3340 python311 - update from 3.11.4 to 3.11.5
  build/python311/build.sh
  build/python311/patches/disable_epoll.patch
  build/python311/patches/mod-posix-sched_priority.patch
  build/python311/patches/static-assert.patch
  build/python311/patches/test-tarfile.patch
  doc/packages.md
Labels: package update, backport-todo

#3341 python39 - update from 3.9.17 to 3.9.18 (r151038)
  build/python39/build.sh
Labels: package update, backport-PR

#3342 python310 - update from 3.10.12 to 3.10.13 (r151044)
  build/python310/build.sh
Labels: package update, backport-PR

#3343 python311 - update from 3.11.4 to 3.11.5 (r151046)
  build/python311/build.sh
Labels: package update, backport-PR

#3345 Core package updates
  build/README.md
  build/brotli/build.sh
  build/coreutils/build.sh
  build/coreutils/patches/install.c.patch
  build/coreutils/patches/man-sections.patch
  build/coreutils/patches/mountlist.c.patch
  build/coreutils/patches/pkglibdir.patch
  build/coreutils/patches/pthread.patch
  build/coreutils/patches/set-permission.c.patch
  build/coreutils/patches/stdbuf.c.patch
  build/coreutils/patches/tests_df_no-mtab-status.sh.patch
  build/coreutils/patches/who.c.patch
  build/coreutils/testsuite.log
  build/git/build.sh
  build/git/testsuite.log
  build/gzip/build.sh
  build/gzip/testsuite.log
  build/libedit/build.sh
  build/libedit/patches/ncurses.patch
  build/libedit/patches/sysmacros.patch
  build/libmpfr/build.sh
  build/libmpfr/testsuite.log
  build/mercurial/build.sh
  build/nss/build.sh
  build/sqlite3/build.sh
  build/zlib/build.sh
  build/zlib/testsuite.log
  doc/packages.md
Labels: package update
