Repository omniosorg/omnios-build, pull requests merged in 2023-12, with the labels that each got.

#3408 openjdk17: update to 17.0.9+9 (r151046)
  build/openjdk17/build.sh
  build/openjdk17/patches/README.txt
  build/openjdk17/patches/illumos-port-1.patch
  build/openjdk17/patches/illumos-port-12.patch
  build/openjdk17/patches/illumos-port-13.patch
  build/openjdk17/patches/illumos-port-14.patch
  build/openjdk17/patches/illumos-port-15.patch
  build/openjdk17/patches/illumos-port-16.patch
  build/openjdk17/patches/illumos-port-17.patch
  build/openjdk17/patches/illumos-port-6.patch
  build/openjdk17/patches/illumos-port-7.patch
  build/openjdk17/patches/illumos-port-8.patch
  build/openjdk17/patches/illumos-port-9.patch
  build/openjdk17/patches/illumos-signal-1.patch
  build/openjdk17/patches/illumos-signal-2.patch
  build/openjdk17/patches/illumos-signal-3.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk17/patches/series
  build/openjdk17/patches/tribblix-flags-cflags.patch
Labels: package update, backport-PR

#3407 Core package updates
  build/git/build.sh
  build/git/testsuite.log
  build/libxml2/build.sh
  build/libxml2/testsuite.log
  build/nss/build.sh
  build/nss/patches/aarch64.patch
  build/nss/patches/shadowing.patch
  build/perl/build.sh
  build/sqlite3/build.sh
  doc/packages.md
Labels: package update

#3409 openjdk17: update to 17.0.9+9
  build/openjdk17/build.sh
  build/openjdk17/patches/README.txt
  build/openjdk17/patches/illumos-port-1.patch
  build/openjdk17/patches/illumos-port-12.patch
  build/openjdk17/patches/illumos-port-13.patch
  build/openjdk17/patches/illumos-port-14.patch
  build/openjdk17/patches/illumos-port-15.patch
  build/openjdk17/patches/illumos-port-16.patch
  build/openjdk17/patches/illumos-port-17.patch
  build/openjdk17/patches/illumos-port-6.patch
  build/openjdk17/patches/illumos-port-7.patch
  build/openjdk17/patches/illumos-port-8.patch
  build/openjdk17/patches/illumos-port-9.patch
  build/openjdk17/patches/illumos-signal-1.patch
  build/openjdk17/patches/illumos-signal-2.patch
  build/openjdk17/patches/illumos-signal-3.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk17/patches/series
  build/openjdk17/patches/tribblix-flags-cflags.patch
  doc/packages.md
Labels: package update, backport-todo

#3415 OpenJDK package updates (r151046)
  build/openjdk11/build.sh
  build/openjdk11/patches/series
  build/openjdk11/patches/tribblix-thrstat001.patch
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3418 curl - update from 8.4.0 to 8.5.0 (r151046)
  build/curl/build.sh
Labels: package update, backport-PR

#3420 curl - update from 8.4.0 to 8.5.0
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3421 python311 - update from 3.11.6 to 3.11.7
  build/python311/build.sh
  build/python311/patches/cross-aarch64.patch
  build/python311/patches/disable_epoll.patch
  build/python311/patches/revert-makedirs.patch
  build/python311/patches/series
  build/python311/patches/test-email.patch
  build/python311/patches/test-filecomments.patch
  build/python311/patches/test-freeze.patch
  build/python311/patches/test-processgroup.patch
  build/python311/patches/test-termios.patch
  build/python311/patches/test-vmlimit.patch
  build/python311/testsuite.log
  doc/packages.md
Labels: package update

#3417 curl - update from 8.4.0 to 8.5.0 (r151038)
  build/curl/build.sh
Labels: package update, backport-PR

#3425 libxml2 - update from 2.12.1 to 2.12.3
  build/libxml2/build.sh
  doc/packages.md
Labels: package update

#3426 Core package updates
  build/chrony/build.sh
  build/chrony/testsuite.log
  build/glib/build.sh
  build/glib/testsuite.log
  build/mercurial/build.sh
  build/rsyslog/build.sh
  build/rsyslog/testsuite.log
  build/sudo/build.sh
  build/vim/build.sh
  build/vim/patches/dtrace.patch
  doc/packages.md
Labels: package update

#3429 openssh - update from 9.4p1 to 9.6p1 (r151048)
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/series
  build/openssh/patches/zlib-check.patch
Labels: package update, backport-PR

#3430 openssh - update from 9.3p2 to 9.6p1 (r151038)
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/series
  build/openssh/patches/sk-dummy-openssl.patch
Labels: package update, backport-PR

#3428 openssh - update from 9.3p2 to 9.6p1 (r151046)
  build/openssh/build.sh
  build/openssh/patches/0001-Skip-config-check.patch
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0007-DTrace-support-for-SFTP.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/series
  build/openssh/patches/sk-dummy-openssl.patch
  build/openssh/patches/sshd_config.patch
  build/openssh/patches/test.patch
Labels: package update, backport-PR

#3427 openssh - update from 9.5p1 to 9.6p1
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  doc/packages.md
Labels: package update, backport-todo

#3434 When compiling python modules, always force rebuild and timestamp mode (r151048)
  build/python311/build.sh
  lib/functions.sh
Labels: backport-PR

#3435 When compiling python modules, always force rebuild and timestamp mode (r151046)
  build/python311/build.sh
  lib/functions.sh
Labels: backport-PR
