Repository omniosorg/omnios-build, pull requests merged in 2023-07, with the labels that each got.

#3285 openssh - update from 8.5p1 to 9.3p2 (r151038)
  build/openssh/build.sh
  build/openssh/patches/0001-Skip-config-check.patch
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0007-DTrace-support-for-SFTP.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/CVE-2021-41617.patch
  build/openssh/patches/revert-dscp.patch
  build/openssh/patches/series
  build/openssh/patches/sk-dummy-openssl.patch
Labels: package update, backport-PR

#3288 openssh - update from 9.3p1 to 9.3p2
  build/openssh/build.sh
  build/openssh/patches/0001-Skip-config-check.patch
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0007-DTrace-support-for-SFTP.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/sk-dummy-openssl.patch
  build/openssh/patches/sshd_config.patch
  build/openssh/patches/test.patch
  doc/packages.md
Labels: package update, backport-todo

#3287 openssh - update from 9.3p1 to 9.3p2 (r151046)
  build/openssh/build.sh
  build/openssh/patches/0001-Skip-config-check.patch
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0007-DTrace-support-for-SFTP.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/sk-dummy-openssl.patch
  build/openssh/patches/sshd_config.patch
  build/openssh/patches/test.patch
Labels: package update, backport-PR

#3286 openssh - update from 9.0p1 to 9.3p2 (r151044)
  build/openssh/build.sh
  build/openssh/patches/0001-Skip-config-check.patch
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0003-lastlogin.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0007-DTrace-support-for-SFTP.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0009-PAM-conversation-fix.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch
  build/openssh/patches/0016-PAM-setcred-failures.patch
  build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch
  build/openssh/patches/0018-Per-session-xauthfile.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch
  build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  build/openssh/patches/sk-dummy-openssl.patch
  build/openssh/patches/sshd_config.patch
  build/openssh/patches/test.patch
Labels: package update, backport-PR

#3289 pyyaml-311: update to 6.0.1
  build/python311/pyyaml/build.sh
  doc/baseline.aarch64
  doc/packages.md
Labels: backport-todo

#3290 pyyaml-311: update to 6.0.1 (r151046)
  build/python311/pyyaml/build.sh
Labels: backport-PR

#3291 pyyaml-310: update to 6.0.1 (r151044)
  build/python310/pyyaml/build.sh
Labels: backport-PR

#3295 openjdk updates (r151046)
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
Labels: package update, backport-PR

#3296 openjdk updates
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
  doc/packages.md
Labels: package update, backport-todo

#3297 openjdk updates (r151044)
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk17/build.sh
  build/openjdk17/patches/java-solaris-sparc.patch
Labels: package update, backport-PR

#3298 openjdk11: update to 11.0.20+8 (r151038)
  build/openjdk11/build.sh
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
Labels: package update, backport-PR
