Repository omniosorg/omnios-build, pull requests merged in 2023-04, with the labels that each got.

#3149 fastjson: update from 0.99.9 to 0.99.9.1
  build/rsyslog/build.sh
  doc/packages.md
Labels: package update, backport-todo

#3150 fastjson: update from 0.99.9 to 0.99.9.1 (r151042)
  build/rsyslog/build.sh
Labels: package update, backport-PR

#3151 fastjson: update from 0.99.9 to 0.99.9.1 (r151044)
  build/rsyslog/build.sh
Labels: package update, backport-PR

#3152 fastjson: update from 0.99.9 to 0.99.9.1 (r151046)
  build/rsyslog/build.sh
Labels: package update, backport-PR

#3153 fastjson: update from 0.99.9 to 0.99.9.1 (r151038)
  build/rsyslog/build.sh
Labels: package update, backport-PR

#3159 zstd: update to 1.5.5 (r151038)
  build/zstd/build.sh
Labels: backport-PR

#3158 zstd: update to 1.5.5 (r151042)
  build/zstd/build.sh
Labels: backport-PR

#3156 zstd: update to 1.5.5 (r151046)
  build/zstd/build.sh
Labels: backport-PR

#3155 zstd: update to 1.5.5 (r151044)
  build/zstd/build.sh
Labels: backport-PR

#3168 python311 - update from 3.11.2 to 3.11.3 (r151046)
  build/python311/build.sh
  build/python311/patches/test-freeze.patch
Labels: package update, backport-PR

#3170 python310 - update from 3.10.9 to 3.10.11 (r151042)
  build/python310/build.sh
  build/python310/patches/enable-ossaudiodev.patch
  build/python310/patches/mod-socket-xpg6.patch
  build/python310/patches/module-dlpi.patch
  build/python310/patches/module-priv-rbac.patch
  build/python310/patches/module-ucred.patch
  build/python310/patches/setup.patch
  build/python310/patches/test-zipfile.patch
Labels: package update, backport-PR

#3169 python310 - update from 3.10.9 to 3.10.11 (r151044)
  build/python310/build.sh
  build/python310/patches/enable-ossaudiodev.patch
  build/python310/patches/mod-socket-xpg6.patch
  build/python310/patches/module-dlpi.patch
  build/python310/patches/module-priv-rbac.patch
  build/python310/patches/module-ucred.patch
  build/python310/patches/setup.patch
  build/python310/patches/test-zipfile.patch
Labels: package update, backport-PR

#3167 python311 - update from 3.11.2 to 3.11.3
  build/python311/build.sh
  build/python311/patches/test-freeze.patch
  doc/packages.md
Labels: package update, backport-todo

#3174 libxml2 - update from 2.10.3 to 2.10.4 (r151042)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3176 libxml2 - update from 2.10.3 to 2.10.4 (r151044)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3177 libxml2 - update from 2.10.3 to 2.10.4 (r151038)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3173 libxml2 - update from 2.10.3 to 2.10.4
  build/libxml2/build.sh
  build/libxml2/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3175 libxml2 - update from 2.10.3 to 2.10.4 (r151046)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3181 sysroot: use a zone image not a full image
  lib/functions.sh
Labels: backport-todo

#3180 sysroot: use a zone image not a full image (r151046)
  lib/functions.sh
Labels: backport-PR

#3184 coreutils - update from 9.2 to 9.3
  build/coreutils/build.sh
  build/coreutils/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3183 coreutils - update from 9.2 to 9.3 (r151046)
  build/coreutils/build.sh
Labels: package update, backport-PR

#3190 clear_archflags is a little over-zealous (r151046)
  lib/functions.sh
Labels: backport-PR

#3189 clear_archflags is a little over-zealous
  lib/functions.sh
Labels: bug, backport-todo

#3201 package updates
  build/bind/build.sh
  build/bind/patches/libs.patch
  build/bind/patches/linker_flags.patch
  build/openjdk11/build.sh
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/omnios-headless.patch
  build/openjdk11/patches/patch-make_GenerateLinkOptData.gmk
  build/openjdk11/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk11/patches/patch-make_autoconf_jdk-options.m4
  build/openjdk11/patches/patch-make_autoconf_lib-x11.m4
  build/openjdk11/patches/patch-make_autoconf_libraries.m4
  build/openjdk11/patches/patch-make_autoconf_toolchain.m4
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcAdlc.gmk
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcDtrace.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_CompileJvm.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_JvmOverrideFiles.gmk
  build/openjdk11/patches/patch-make_launcher_Launcher-jdk.pack.gmk
  build/openjdk11/patches/patch-make_launcher_LauncherCommon.gmk
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ec.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ucrypto.gmk
  build/openjdk11/patches/patch-make_lib_LibCommon.gmk
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_atomic__solaris__x86.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_bytes__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.cpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_prefetch__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk11/patches/patch-src_hotspot_share_gc_g1_g1Analytics.cpp
  build/openjdk11/patches/patch-src_hotspot_share_utilities_globalDefinitions__gcc.hpp
  build/openjdk11/patches/patch-src_java.base_solaris_native_libnio_ch_DevPollArrayWrapper.c
  build/openjdk11/patches/patch-src_java.desktop_share_native_libsplashscreen_libpng_pngpriv.h
  build/openjdk11/patches/patch-src_jdk.crypto.ec_share_native_libsunec_ECC__JNI.cpp
  build/openjdk11/patches/security-pkcs11.patch
  build/openjdk11/patches/tribblix-Launcher-jdk.patch
  build/openjdk11/patches/tribblix-LauncherCommon.patch
  build/openjdk11/patches/tribblix-agent-mt.patch
  build/openjdk11/patches/tribblix-attachListener_solaris.patch
  build/openjdk11/patches/tribblix-demangle1.patch
  build/openjdk11/patches/tribblix-demangle2.patch
  build/openjdk11/patches/tribblix-demangle3.patch
  build/openjdk11/patches/tribblix-demangle4.patch
  build/openjdk11/patches/tribblix-flags-ldflags.patch
  build/openjdk11/patches/tribblix-flags-ldflags2.patch
  build/openjdk11/patches/tribblix-flags-ldflags3.patch
  build/openjdk17/build.sh
  build/openjdk8/build.sh
  build/perl/build.sh
  build/perl/patches/dtrace.patch
  build/perl/patches/t_op_getppid.t.patch
  build/perl/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3202 package updates (r151046)
  build/bind/build.sh
  build/bind/patches/libs.patch
  build/bind/patches/linker_flags.patch
  build/openjdk11/build.sh
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/omnios-headless.patch
  build/openjdk11/patches/patch-make_GenerateLinkOptData.gmk
  build/openjdk11/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk11/patches/patch-make_autoconf_jdk-options.m4
  build/openjdk11/patches/patch-make_autoconf_lib-x11.m4
  build/openjdk11/patches/patch-make_autoconf_libraries.m4
  build/openjdk11/patches/patch-make_autoconf_toolchain.m4
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcAdlc.gmk
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcDtrace.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_CompileJvm.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_JvmOverrideFiles.gmk
  build/openjdk11/patches/patch-make_launcher_Launcher-jdk.pack.gmk
  build/openjdk11/patches/patch-make_launcher_LauncherCommon.gmk
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ec.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ucrypto.gmk
  build/openjdk11/patches/patch-make_lib_LibCommon.gmk
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_atomic__solaris__x86.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_bytes__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.cpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_prefetch__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk11/patches/patch-src_hotspot_share_gc_g1_g1Analytics.cpp
  build/openjdk11/patches/patch-src_hotspot_share_utilities_globalDefinitions__gcc.hpp
  build/openjdk11/patches/patch-src_java.base_solaris_native_libnio_ch_DevPollArrayWrapper.c
  build/openjdk11/patches/patch-src_java.desktop_share_native_libsplashscreen_libpng_pngpriv.h
  build/openjdk11/patches/patch-src_jdk.crypto.ec_share_native_libsunec_ECC__JNI.cpp
  build/openjdk11/patches/security-pkcs11.patch
  build/openjdk11/patches/tribblix-Launcher-jdk.patch
  build/openjdk11/patches/tribblix-LauncherCommon.patch
  build/openjdk11/patches/tribblix-agent-mt.patch
  build/openjdk11/patches/tribblix-attachListener_solaris.patch
  build/openjdk11/patches/tribblix-demangle1.patch
  build/openjdk11/patches/tribblix-demangle2.patch
  build/openjdk11/patches/tribblix-demangle3.patch
  build/openjdk11/patches/tribblix-demangle4.patch
  build/openjdk11/patches/tribblix-flags-ldflags.patch
  build/openjdk11/patches/tribblix-flags-ldflags2.patch
  build/openjdk11/patches/tribblix-flags-ldflags3.patch
  build/openjdk17/build.sh
  build/openjdk8/build.sh
  build/perl/build.sh
  build/perl/patches/dtrace.patch
  build/perl/patches/t_op_getppid.t.patch
  build/perl/testsuite.log
Labels: package update, backport-PR

#3203 package updates (r151044)
  build/openjdk11/build.sh
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/omnios-headless.patch
  build/openjdk11/patches/patch-make_GenerateLinkOptData.gmk
  build/openjdk11/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk11/patches/patch-make_autoconf_jdk-options.m4
  build/openjdk11/patches/patch-make_autoconf_lib-x11.m4
  build/openjdk11/patches/patch-make_autoconf_libraries.m4
  build/openjdk11/patches/patch-make_autoconf_toolchain.m4
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcAdlc.gmk
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcDtrace.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_CompileJvm.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_JvmOverrideFiles.gmk
  build/openjdk11/patches/patch-make_launcher_Launcher-jdk.pack.gmk
  build/openjdk11/patches/patch-make_launcher_LauncherCommon.gmk
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ec.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ucrypto.gmk
  build/openjdk11/patches/patch-make_lib_LibCommon.gmk
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_atomic__solaris__x86.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_bytes__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.cpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_prefetch__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk11/patches/patch-src_hotspot_share_gc_g1_g1Analytics.cpp
  build/openjdk11/patches/patch-src_hotspot_share_utilities_globalDefinitions__gcc.hpp
  build/openjdk11/patches/patch-src_java.base_solaris_native_libnio_ch_DevPollArrayWrapper.c
  build/openjdk11/patches/patch-src_java.desktop_share_native_libsplashscreen_libpng_pngpriv.h
  build/openjdk11/patches/patch-src_jdk.crypto.ec_share_native_libsunec_ECC__JNI.cpp
  build/openjdk11/patches/security-pkcs11.patch
  build/openjdk11/patches/tribblix-Launcher-jdk.patch
  build/openjdk11/patches/tribblix-LauncherCommon.patch
  build/openjdk11/patches/tribblix-agent-mt.patch
  build/openjdk11/patches/tribblix-attachListener_solaris.patch
  build/openjdk11/patches/tribblix-demangle1.patch
  build/openjdk11/patches/tribblix-demangle2.patch
  build/openjdk11/patches/tribblix-demangle3.patch
  build/openjdk11/patches/tribblix-demangle4.patch
  build/openjdk11/patches/tribblix-flags-ldflags.patch
  build/openjdk11/patches/tribblix-flags-ldflags2.patch
  build/openjdk11/patches/tribblix-flags-ldflags3.patch
  build/openjdk17/build.sh
  build/openjdk8/build.sh
  build/perl/build.sh
  build/perl/patches/dtrace.patch
  build/perl/patches/t_op_getppid.t.patch
  build/perl/testsuite.log
Labels: package update, backport-PR

#3204 package updates (r151042)
  build/openjdk11/build.sh
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/omnios-headless.patch
  build/openjdk11/patches/patch-make_GenerateLinkOptData.gmk
  build/openjdk11/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk11/patches/patch-make_autoconf_jdk-options.m4
  build/openjdk11/patches/patch-make_autoconf_lib-x11.m4
  build/openjdk11/patches/patch-make_autoconf_libraries.m4
  build/openjdk11/patches/patch-make_autoconf_toolchain.m4
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcAdlc.gmk
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcDtrace.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_CompileJvm.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_JvmOverrideFiles.gmk
  build/openjdk11/patches/patch-make_launcher_Launcher-jdk.pack.gmk
  build/openjdk11/patches/patch-make_launcher_LauncherCommon.gmk
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ec.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ucrypto.gmk
  build/openjdk11/patches/patch-make_lib_LibCommon.gmk
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_atomic__solaris__x86.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_bytes__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.cpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_prefetch__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk11/patches/patch-src_hotspot_share_gc_g1_g1Analytics.cpp
  build/openjdk11/patches/patch-src_hotspot_share_utilities_globalDefinitions__gcc.hpp
  build/openjdk11/patches/patch-src_java.base_solaris_native_libnio_ch_DevPollArrayWrapper.c
  build/openjdk11/patches/patch-src_java.desktop_share_native_libsplashscreen_libpng_pngpriv.h
  build/openjdk11/patches/patch-src_jdk.crypto.ec_share_native_libsunec_ECC__JNI.cpp
  build/openjdk11/patches/security-pkcs11.patch
  build/openjdk11/patches/tribblix-Launcher-jdk.patch
  build/openjdk11/patches/tribblix-LauncherCommon.patch
  build/openjdk11/patches/tribblix-agent-mt.patch
  build/openjdk11/patches/tribblix-attachListener_solaris.patch
  build/openjdk11/patches/tribblix-demangle1.patch
  build/openjdk11/patches/tribblix-demangle2.patch
  build/openjdk11/patches/tribblix-demangle3.patch
  build/openjdk11/patches/tribblix-demangle4.patch
  build/openjdk11/patches/tribblix-flags-ldflags.patch
  build/openjdk11/patches/tribblix-flags-ldflags2.patch
  build/openjdk11/patches/tribblix-flags-ldflags3.patch
  build/openjdk17/build.sh
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3205 package updates (r151038)
  build/openjdk11/build.sh
  build/openjdk11/patches/fontpath.patch
  build/openjdk11/patches/illumos-port-6.patch
  build/openjdk11/patches/omnios-headless.patch
  build/openjdk11/patches/patch-make_GenerateLinkOptData.gmk
  build/openjdk11/patches/patch-make_autoconf_flags-cflags.m4
  build/openjdk11/patches/patch-make_autoconf_jdk-options.m4
  build/openjdk11/patches/patch-make_autoconf_lib-x11.m4
  build/openjdk11/patches/patch-make_autoconf_libraries.m4
  build/openjdk11/patches/patch-make_autoconf_toolchain.m4
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcAdlc.gmk
  build/openjdk11/patches/patch-make_hotspot_gensrc_GensrcDtrace.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_CompileJvm.gmk
  build/openjdk11/patches/patch-make_hotspot_lib_JvmOverrideFiles.gmk
  build/openjdk11/patches/patch-make_launcher_Launcher-jdk.pack.gmk
  build/openjdk11/patches/patch-make_launcher_LauncherCommon.gmk
  build/openjdk11/patches/patch-make_lib_Awt2dLibraries.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ec.gmk
  build/openjdk11/patches/patch-make_lib_Lib-jdk.crypto.ucrypto.gmk
  build/openjdk11/patches/patch-make_lib_LibCommon.gmk
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_atomic__solaris__x86.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_bytes__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.cpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_os__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os__cpu_solaris__x86_prefetch__solaris__x86.inline.hpp
  build/openjdk11/patches/patch-src_hotspot_os_solaris_os__solaris.cpp
  build/openjdk11/patches/patch-src_hotspot_share_gc_g1_g1Analytics.cpp
  build/openjdk11/patches/patch-src_hotspot_share_utilities_globalDefinitions__gcc.hpp
  build/openjdk11/patches/patch-src_java.base_solaris_native_libnio_ch_DevPollArrayWrapper.c
  build/openjdk11/patches/patch-src_java.desktop_share_native_libsplashscreen_libpng_pngpriv.h
  build/openjdk11/patches/patch-src_jdk.crypto.ec_share_native_libsunec_ECC__JNI.cpp
  build/openjdk11/patches/security-pkcs11.patch
  build/openjdk11/patches/tribblix-Launcher-jdk.patch
  build/openjdk11/patches/tribblix-LauncherCommon.patch
  build/openjdk11/patches/tribblix-agent-mt.patch
  build/openjdk11/patches/tribblix-attachListener_solaris.patch
  build/openjdk11/patches/tribblix-demangle1.patch
  build/openjdk11/patches/tribblix-demangle2.patch
  build/openjdk11/patches/tribblix-demangle3.patch
  build/openjdk11/patches/tribblix-demangle4.patch
  build/openjdk11/patches/tribblix-flags-ldflags.patch
  build/openjdk11/patches/tribblix-flags-ldflags2.patch
  build/openjdk11/patches/tribblix-flags-ldflags3.patch
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3206 git - update from 2.35.7 to 2.35.8 (r151042)
  build/git/build.sh
Labels: package update, backport-PR

#3207 git - update from 2.37.6 to 2.37.7 (r151044)
  build/git/build.sh
Labels: package update, backport-PR

#3208 git - update from 2.31.7 to 2.31.8 (r151038)
  build/git/build.sh
Labels: package update, backport-PR
