Repository omniosorg/omnios-build, pull requests merged in 2024-01, with the labels that each got.

#3440 Lock cloud-init external dependency versions (r151046)
  build/cloud-init/patches/requirements.patch
  build/cloud-init/patches/series
Labels: backport-PR

#3444 Core package updates
  build/ntpsec/build.sh
  build/ntpsec/local.mog
  build/ntpsec/patches/asciidoc.patch
  build/ntpsec/patches/clockwork.patch
  build/ntpsec/patches/conf.patch
  build/ntpsec/patches/nonet.patch
  build/ntpsec/patches/pie.patch
  build/ntpsec/patches/series
  build/ntpsec/patches/unneeded_libs.patch
  build/ntpsec/testsuite.log
  build/sudo/build.sh
  build/swig/build.sh
  build/swig/patches/unneeded-libs.patch
  build/swig/testsuite.log
  doc/packages.md
Labels: package update

#3445 Core package updates
  build/XML::Parser/build.sh
  build/libtool/build.sh
  build/mercurial/build.sh
  build/python311/attrs/build.sh
  doc/packages.md
  lib/functions.sh
Labels: package update

#3447 Core package updates
  build/bash/build.sh
  build/bash/patches/bash-5.2-patches/bash52-022
  build/bash/patches/bash-5.2-patches/bash52-023
  build/bash/patches/bash-5.2-patches/bash52-024
  build/bash/patches/bash-5.2-patches/bash52-025
  build/bash/patches/bash-5.2-patches/bash52-026
  build/bash/patches/fetch-patches
  build/bash/patches/series
  build/iso-codes/build.sh
  build/libidn/build.sh
  build/libxml2/build.sh
  build/libxml2/testsuite.log
  build/sqlite3/build.sh
  doc/packages.md
Labels: package update

#3449 unzip was not building with bzip2 support
  build/unzip/build.sh
  build/unzip/patches/CVE-2014-8139-crc-overflow.patch
  build/unzip/patches/CVE-2014-8140-test-compr-eb.patch
  build/unzip/patches/CVE-2014-8141-getzip64data.patch
  build/unzip/patches/CVE-2014-9636-test-compr-eb.patch
  build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch
  build/unzip/patches/CVE-2015-7696-heap-overflow.patch
  build/unzip/patches/CVE-2015-7697-infinite-loop.patch
  build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch
  build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch
  build/unzip/patches/CVE-2019-13232a.patch
  build/unzip/patches/CVE-2019-13232b.patch
  build/unzip/patches/CVE-2019-13232c.patch
  build/unzip/patches/CVE-2019-13232d.patch
  build/unzip/patches/CVE-2019-13232e.patch
  build/unzip/patches/CVE-2021-4217.patch
  build/unzip/patches/CVE-2022-0529-0530.patch
  build/unzip/patches/configure.patch
  build/unzip/patches/fileio-big-files.patch
  build/unzip/patches/integer-underflow-csiz_decrypted.patch
  build/unzip/patches/nostrip.patch
  build/unzip/patches/series
  build/unzip/patches/unix_Makefile.patch
Labels: backport-todo

#3452 unzip: backport fixes from bloody (r151046)
  build/unzip/build.sh
  build/unzip/patches/CVE-2014-8139-crc-overflow.patch
  build/unzip/patches/CVE-2014-8140-test-compr-eb.patch
  build/unzip/patches/CVE-2014-8141-getzip64data.patch
  build/unzip/patches/CVE-2014-9636-test-compr-eb.patch
  build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch
  build/unzip/patches/CVE-2015-7696-heap-overflow.patch
  build/unzip/patches/CVE-2015-7697-infinite-loop.patch
  build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch
  build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch
  build/unzip/patches/CVE-2019-13232a.patch
  build/unzip/patches/CVE-2019-13232b.patch
  build/unzip/patches/CVE-2019-13232c.patch
  build/unzip/patches/CVE-2019-13232d.patch
  build/unzip/patches/CVE-2019-13232e.patch
  build/unzip/patches/CVE-2021-4217.patch
  build/unzip/patches/CVE-2022-0529-0530.patch
  build/unzip/patches/configure.patch
  build/unzip/patches/fileio-big-files.patch
  build/unzip/patches/integer-underflow-csiz_decrypted.patch
  build/unzip/patches/nostrip.patch
  build/unzip/patches/series
  build/unzip/patches/unix_Makefile.patch
Labels: package update, backport-PR

#3451 unzip: backport fixes from bloody (r151048)
  build/unzip/build.sh
  build/unzip/patches/CVE-2014-8139-crc-overflow.patch
  build/unzip/patches/CVE-2014-8140-test-compr-eb.patch
  build/unzip/patches/CVE-2014-8141-getzip64data.patch
  build/unzip/patches/CVE-2014-9636-test-compr-eb.patch
  build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch
  build/unzip/patches/CVE-2015-7696-heap-overflow.patch
  build/unzip/patches/CVE-2015-7697-infinite-loop.patch
  build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch
  build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch
  build/unzip/patches/CVE-2019-13232a.patch
  build/unzip/patches/CVE-2019-13232b.patch
  build/unzip/patches/CVE-2019-13232c.patch
  build/unzip/patches/CVE-2019-13232d.patch
  build/unzip/patches/CVE-2019-13232e.patch
  build/unzip/patches/CVE-2021-4217.patch
  build/unzip/patches/CVE-2022-0529-0530.patch
  build/unzip/patches/configure.patch
  build/unzip/patches/fileio-big-files.patch
  build/unzip/patches/integer-underflow-csiz_decrypted.patch
  build/unzip/patches/nostrip.patch
  build/unzip/patches/series
  build/unzip/patches/unix_Makefile.patch
Labels: package update, backport-PR

#3450 unzip: backport fixes from bloody (r151038)
  build/unzip/build.sh
  build/unzip/patches/CVE-2014-8139-crc-overflow.patch
  build/unzip/patches/CVE-2014-8140-test-compr-eb.patch
  build/unzip/patches/CVE-2014-8141-getzip64data.patch
  build/unzip/patches/CVE-2014-9636-test-compr-eb.patch
  build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch
  build/unzip/patches/CVE-2015-7696-heap-overflow.patch
  build/unzip/patches/CVE-2015-7697-infinite-loop.patch
  build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch
  build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch
  build/unzip/patches/CVE-2019-13232a.patch
  build/unzip/patches/CVE-2019-13232b.patch
  build/unzip/patches/CVE-2019-13232c.patch
  build/unzip/patches/CVE-2019-13232d.patch
  build/unzip/patches/CVE-2019-13232e.patch
  build/unzip/patches/CVE-2021-4217.patch
  build/unzip/patches/CVE-2022-0529-0530.patch
  build/unzip/patches/configure.patch
  build/unzip/patches/fileio-big-files.patch
  build/unzip/patches/integer-underflow-csiz_decrypted.patch
  build/unzip/patches/nostrip.patch
  build/unzip/patches/series
  build/unzip/patches/unix_Makefile.patch
Labels: package update, backport-PR

#3454 zlib - update from 1.3 to 1.3.1 (r151048)
  build/zlib/build.sh
  build/zlib/testsuite.log
Labels: package update, backport-PR

#3453 Core package updates
  build/glib/build.sh
  build/glib/testsuite.log
  build/lzlib/build.sh
  build/lzlib/patches/ld-soname.patch
  build/lzlib/testsuite.log
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  build/nss/build.sh
  build/nss/patches/aarch64.patch
  build/nss/patches/pkcs11v3.patch
  build/nss/patches/shadowing.patch
  build/zlib/build.sh
  build/zlib/testsuite.log
  doc/packages.md
Labels: package update
