Repository omniosorg/omnios-build, pull requests merged in 2024-12, with the labels that each got.

#3754 Core package updates
  build/mercurial/build.sh
  build/pv/build.sh
  build/python312/build.sh
  build/python312/patches/disable_epoll.patch
  build/python312/patches/gethostbyname.patch
  build/python312/patches/locale-encoding.patch
  build/python312/patches/posix_spawn-close_fds-support.patch
  build/python312/testsuite.log
  build/rsyslog/build.sh
  build/rsyslog/testsuite.log
  build/tcsh/build.sh
  build/tcsh/testsuite.log
  doc/packages.md
Labels: package update

#3763 curl - update from 8.11.0 to 8.11.1
  build/curl/build.sh
  build/curl/patches/ldap.patch
  build/curl/patches/series
  build/curl/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3765 curl - update from 8.11.0 to 8.11.1 (r151052)
  build/curl/build.sh
Labels: package update, backport-PR

#3764 curl - update from 8.11.0 to 8.11.1 (r151050)
  build/curl/build.sh
Labels: package update, backport-PR

#3766 curl - update from 8.11.0 to 8.11.1 (r151046)
  build/curl/build.sh
Labels: package update, backport-PR

#3779 perl: Getopt::Long got picky about ignoring case from version 2.55 on (r151052)
  build/perl/patches/getopt.patch
  build/perl/patches/series
Labels: backport-PR

#3784 watch - update from 3.3.16 to 4.0.5
  build/watch/build.sh
  doc/packages.md
Labels: package update

#3782 oqs package updates
  build/liboqs/build.sh
  build/liboqs/patches/testsuite.patch
  build/liboqs/testsuite.log
  build/oqs-provider/build.sh
  doc/packages.md
Labels: package update

#3783 oqs package updates (r151052)
  build/liboqs/build.sh
  build/liboqs/patches/series
  build/liboqs/patches/testsuite.patch
  build/liboqs/testsuite.log
  build/oqs-provider/build.sh
  build/oqs-provider/testsuite.log
Labels: package update, backport-PR
