Repository omniosorg/omnios-build, pull requests merged in 2024-06, with the labels that each got.

#3585 xz - update from 5.6.1 to 5.6.2
  build/xz/build.sh
  build/xz/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3586 xz - update from 5.6.1 to 5.6.2 (r151050)
  build/xz/build.sh
Labels: package update, backport-PR

#3587 openssl - update from 3.1.5 to 3.1.6 (r151050)
  build/openssl/build-3.sh
  build/openssl/testsuite-3.log
Labels: package update, backport-PR

#3588 openssl - update from 3.1.5 to 3.1.6 (r151048)
  build/openssl/build-3.sh
  build/openssl/testsuite-3.log
Labels: package update, backport-PR

#3590 openssl - upate from 3.1.5 to 3.1.6
  build/openssl/build-3.sh
  build/openssl/patches-1.1/CVE-2024-2511.patch
  build/openssl/patches-1.1/CVE-2024-4741.patch
  build/openssl/patches-1.1/series
  build/openssl/testsuite-3.log
  doc/packages.md
Labels: package update, backport-todo

#3589 openssl - update from 3.0.13 to 3.0.14 (r151046)
  build/openssl/build-1.1.sh
  build/openssl/build-3.sh
  build/openssl/patches-1.1/CVE-2024-2511.patch
  build/openssl/patches-1.1/CVE-2024-4741.patch
  build/openssl/patches-1.1/series
  build/openssl/testsuite-3.log
Labels: package update, backport-PR

#3595 openjdk package updates (r151050)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/README.txt
  build/openjdk17/patches/illumos-port-19.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/security-pkcs11.patch
  build/openjdk17/patches/series
  build/openjdk17/patches/tribblix-attachListener_solaris.patch
  build/openjdk21/build.sh
  build/openjdk21/patches/README.txt
  build/openjdk21/patches/illumos-port-4.patch
  build/openjdk21/patches/java-solaris-sparc.patch
  build/openjdk21/patches/security-pkcs11.patch
  build/openjdk21/patches/series
  build/openjdk21/patches/tribblix-attachListener_solaris.patch
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3596 openjdk package updates (r151048)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/README.txt
  build/openjdk17/patches/illumos-port-19.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/security-pkcs11.patch
  build/openjdk17/patches/series
  build/openjdk17/patches/tribblix-attachListener_solaris.patch
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3597 openjdk package updates (r151046)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk17/patches/README.txt
  build/openjdk17/patches/illumos-port-19.patch
  build/openjdk17/patches/java-solaris-sparc.patch
  build/openjdk17/patches/security-pkcs11.patch
  build/openjdk17/patches/series
  build/openjdk17/patches/tribblix-attachListener_solaris.patch
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3603 python312 - update from 3.12.3 to 3.12.4 (r151050)
  build/python312/build.sh
  build/python312/patches/disable_epoll.patch
  build/python312/patches/mod-posix-sched_priority.patch
  build/python312/patches/posix_spawn-close_fds-support.patch
  build/python312/patches/posix_spawn-environment-fix.patch
  build/python312/patches/py_db.patch
  build/python312/patches/revert-makedirs.patch
  build/python312/patches/test-pkgutil.patch
  build/python312/patches/test-tarfile.patch
  build/python312/testsuite.log
Labels: package update, backport-PR

#3609 Core package updates
  build/bash/build.sh
  build/chrony/build.sh
  build/iperf/build.sh
  build/iperf/patches/headers.patch
  build/iperf/patches/series
  build/libxml2/build.sh
  build/libxml2/testsuite.log
  build/pv/build.sh
  doc/packages.md
Labels: package update
