Repository omniosorg/omnios-build, pull requests merged in 2025-05, with the labels that each got.

#3924 screen: fixes for CVE-2025-4680[245] (r151046)
  build/screen/build.sh
  build/screen/patches/0001-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch
  build/screen/patches/0002-Avoid-file-existence-test-information-leaks-to-fix-C.patch
  build/screen/patches/0003-socket.c-don-t-send-signals-with-root-privileges-to-.patch
  build/screen/patches/series
Labels: package update, backport-PR

#3922 screen: fixes for CVE-2025-4680[245] (r151054)
  build/screen/build.sh
  build/screen/patches/0001-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch
  build/screen/patches/0002-Avoid-file-existence-test-information-leaks-to-fix-C.patch
  build/screen/patches/0003-socket.c-don-t-send-signals-with-root-privileges-to-.patch
  build/screen/patches/series
Labels: package update, backport-PR

#3921 screen: fixes for CVE-2025-4680[245]
  build/screen/patches/0001-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch
  build/screen/patches/0002-Avoid-file-existence-test-information-leaks-to-fix-C.patch
  build/screen/patches/0003-socket.c-don-t-send-signals-with-root-privileges-to-.patch
  build/screen/patches/series
Labels: package update, backport-todo

#3925 Core package updates
  build/bind/build.sh
  build/coreutils/build.sh
  build/coreutils/patches/getlocalename.patch
  build/coreutils/patches/mountlist.c.patch
  build/coreutils/patches/series
  build/coreutils/patches/who.c.patch
  build/coreutils/testsuite.log
  build/diffutils/build.sh
  build/diffutils/patches/getlocalename.patch
  build/diffutils/patches/series
  build/diffutils/testsuite.log
  build/fio/build.sh
  build/gawk/build.sh
  build/gawk/testsuite.log
  build/gettext/build.sh
  build/gettext/patches/configure.patch
  build/gettext/patches/series
  build/gettext/testsuite.log
  build/iso-codes/build.sh
  build/less/build.sh
  build/mercurial/build.sh
  build/nss/build.sh
  build/ntpsec/build.sh
  build/ntpsec/patches/asciidoc.patch
  build/ntpsec/patches/conf.patch
  build/ntpsec/patches/nonet.patch
  build/ntpsec/patches/pie.patch
  build/ntpsec/patches/unneeded_libs.patch
  build/ntpsec/testsuite.log
  build/rsyslog/build.sh
  build/rsyslog/patches/man.patch
  build/rsyslog/testsuite.log
  build/sqlite3/build.sh
  build/sqlite3/patches/cross.patch
  build/sqlite3/patches/series
  build/sqlite3/patches/soname.patch
  build/swig/build.sh
  doc/packages.md
Labels: package update

#3930 jdk updates (r151052)
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk21/build.sh
  build/openjdk21/patches/illumos-jline.patch
  build/openjdk21/patches/illumos-port-28.patch
  build/openjdk21/patches/restore_os_cpu_solaris_x86.patch
  build/openjdk21/patches/series
  build/openjdk8/build.sh
Labels: package update, backport-PR

#3929 jdk updates
  build/openjdk11/build.sh
  build/openjdk17/build.sh
  build/openjdk21/build.sh
  build/openjdk21/patches/illumos-jline.patch
  build/openjdk21/patches/illumos-port-28.patch
  build/openjdk21/patches/restore_os_cpu_solaris_x86.patch
  build/openjdk21/patches/series
  build/openjdk8/build.sh
  doc/packages.md
Labels: package update, backport-todo

#3937 curl - update from 8.12.0 to 8.14.0 (r151052)
  build/curl/build.sh
Labels: package update, backport-PR

#3935 curl - update from 8.13.0 to 8.14.0 (r151054)
  build/curl/build.sh
Labels: package update, backport-PR

#3934 libxml2 - update from 2.13.6 to 2.13.8 (r151052)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3933 libxml2 - update from 2.13.6 to 2.13.8 (r151054)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3936 curl - update from 8.12.0 to 8.14.0 (r151046)
  build/curl/build.sh
Labels: package update, backport-PR
