Repository omniosorg/omnios-build, pull requests merged in 2025-02, with the labels that each got.

#3833 curl - update from 8.11.1 to 8.12.0 (r151052)
  build/curl/build.sh
Labels: package update, backport-PR

#3832 curl - update from 8.11.1 to 8.12.0 (r151046)
  build/curl/build.sh
Labels: package update, backport-PR

#3831 curl - update from 8.11.1 to 8.12.0 (r151050)
  build/curl/build.sh
Labels: package update, backport-PR

#3834 curl - update from 8.11.1 to 8.12.0
  build/curl/build.sh
  build/curl/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3836 add dtc
  build/dtc/build.sh
  build/dtc/local.mog
  build/entire/entire-aarch64.pkg
  doc/baseline
  doc/baseline.aarch64
  doc/packages.md
  doc/pkglist.aarch64
Labels: backport-todo

#3837 add dtc (r151052)
  build/dtc/build.sh
  build/dtc/local.mog
  build/entire/entire-aarch64.pkg
  doc/baseline
  doc/baseline.aarch64
  doc/pkglist.aarch64
Labels: backport-PR

#3838 add dtc (r151050)
  build/dtc/build.sh
  build/dtc/local.mog
  build/entire/entire-aarch64.pkg
  doc/baseline
  doc/baseline.aarch64
  doc/pkglist.aarch64
Labels: backport-PR

#3839 add dtc (r151046)
  build/dtc/build.sh
  build/dtc/local.mog
  doc/baseline
  doc/baseline.aarch64
  doc/pkglist.aarch64
Labels: backport-PR

#3841 python313 - update from 3.13.1 to 3.13.2
  build/python313/build.sh
  build/python313/patches/disable_epoll.patch
  build/python313/patches/fancy-termios.patch
  build/python313/patches/gethostbyname.patch
  build/python313/patches/illumos.patch
  build/python313/patches/locale-encoding.patch
  build/python313/patches/mod-posix-sched_priority.patch
  build/python313/patches/restore-dtrace.patch
  build/python313/patches/series
  build/python313/patches/test-freeze.patch
  build/python313/patches/test-opts.patch
  build/python313/patches/test-zipfile.patch
  build/python313/testsuite.log
  doc/packages.md
Labels: package update

#3846 openssl - update from 3.3.2 to 3.3.3 (r151052)
  build/openssl/build-3.sh
  build/openssl/testsuite-3.log
Labels: package update, backport-PR

#3854 chrony - update from 4.5 to 4.6.1
  build/chrony/build.sh
  build/chrony/patches/local.patch
  build/chrony/patches/series
  build/chrony/testsuite.log
  doc/packages.md
Labels: package update

#3857 openssh - update from 9.9p1 to 9.9p2 (r151052)
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
Labels: package update, backport-PR

#3856 openssh - update from 9.9p1 to 9.9p2
  build/openssh/build.sh
  build/openssh/patches/0002-PAM-Support.patch
  build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch
  build/openssh/patches/0008-Add-DisableBanner-option.patch
  build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch
  build/openssh/patches/0013-Solaris-Auditing-support.patch
  build/openssh/patches/0019-PubKeyPlugin-support.patch
  build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch
  build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch
  build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
  doc/packages.md
Labels: package update, backport-todo

#3860 libxml2 - update from 2.13.5 to 2.13.6
  build/libxml2/build.sh
  doc/packages.md
Labels: package update, backport-todo

#3859 openssh: Fixes for CVE-2025-2646[56] (r151050)
  build/openssh/build.sh
  build/openssh/patches/CVE-2025-26465.patch
  build/openssh/patches/CVE-2025-26466.patch
  build/openssh/patches/series
  build/openssh/patches/series.aarch64
Labels: package update, backport-PR

#3858 openssh: Fixes for CVE-2025-2646[56] (r151046)
  build/openssh/build.sh
  build/openssh/patches/CVE-2025-26465.patch
  build/openssh/patches/CVE-2025-26466.patch
  build/openssh/patches/series
  build/openssh/patches/series.aarch64
  build/openssh/testsuite.log
Labels: package update, backport-PR

#3863 libxml2 - update from 2.11.7 to 2.12.10 (r151046)
  build/libxml2/build.sh
  build/libxml2/testsuite.log
Labels: package update, backport-PR

#3862 libxml2 - update from 2.12.6 to 2.12.10 (r151050)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3861 libxml2 - update from 2.13.4 to 2.13.6 (r151052)
  build/libxml2/build.sh
Labels: package update, backport-PR

#3868 Core package updates
  build/bind/build.sh
  build/curl/build.sh
  build/fio/build.sh
  build/glib/build.sh
  build/glib/patches/sigstack.patch
  build/glib/testsuite.log
  build/rsyslog/build.sh
  build/rsyslog/patches/runtime-rsyslog.h.patch
  build/rsyslog/patches/test.patch
  build/rsyslog/testsuite.log
  build/socat/build.sh
  build/sqlite3/build.sh
  build/sqlite3/patches/cross.patch
  build/sqlite3/patches/nostrip.patch
  doc/packages.md
Labels: package update
