Repository omniosorg/omnios-build, pull requests merged in 2025-01, with the labels that each got.

#3801 git - update from 2.44.2 to 2.44.3 (r151050)
  build/git/build.sh
Labels: package update, backport-PR

#3802 git - update from 2.40.3 to 2.40.4 (r151046)
  build/git/build.sh
Labels: package update, backport-PR

#3804 rsync - update from 3.3.0 to 3.4.0 (r151052)
  build/rsync/build.sh
  build/rsync/patches/gcc14.patch
  build/rsync/testsuite.log
Labels: package update, backport-PR

#3805 rsync - update from 3.2.7 to 3.4.0 (r151050)
  build/rsync/build.sh
  build/rsync/testsuite.log
Labels: package update, backport-PR

#3806 rsync - update from 3.2.7 to 3.4.0 (r151046)
  build/rsync/build.sh
  build/rsync/testsuite.log
Labels: package update, backport-PR

#3807 rsync - update from 3.3.0 to 3.4.0
  build/rsync/build.sh
  build/rsync/patches/gcc14.patch
  build/rsync/testsuite.log
  doc/packages.md
Labels: package update, backport-todo

#3799 git - update from 2.46.2 to 2.46.3 (r151052)
  build/git/build.sh
Labels: package update, backport-PR

#3808 aarch64: update binutils to 2.41
  build/binutils/build-arch-aarch64.sh
Labels: package update

#3809 rsync - update from 3.4.0 to 3.4.1 (r151052)
  build/rsync/build.sh
  build/rsync/patches/gcc14.patch
  build/rsync/patches/series
Labels: package update, backport-PR

#3810 rsync - update from 3.4.0 to 3.4.1 (r151050)
  build/rsync/build.sh
Labels: package update, backport-PR

#3811 rsync - update from 3.4.0 to 3.4.1 (r151046)
  build/rsync/build.sh
Labels: package update, backport-PR

#3812 rsync - update from 3.4.0 to 3.4.1
  build/rsync/build.sh
  build/rsync/patches/gcc14.patch
  build/rsync/patches/series
  doc/packages.md
Labels: package update, backport-todo

#3815 perl: update to 5.38.3 (r151050)
  build/perl/build.sh
  build/perl/patches-aarch64/perl-5.40.1.patch
  build/perl/patches-aarch64/series
Labels: package update

#3814 perl: update to 5.40.1 (r151052)
  build/perl/build.sh
  build/perl/patches-aarch64/perl-5.40.1.patch
  build/perl/patches-aarch64/series
  build/perl/testsuite.log
Labels: package update, backport-PR
