Repository omniosorg/omnios-build, pull requests merged in 2025-04, with the labels that each got.

#3891 Core package updates
  build/bind/build.sh
  build/dbus-glib/build.sh
  build/dbus-glib/local.mog
  build/git/build.sh
  build/git/testsuite.log
  build/libidn/build.sh
  build/libidn/local.mog
  build/libmpfr/build.sh
  build/mercurial/build.sh
  build/nghttp2/build.sh
  build/nghttp2/testsuite.log
  build/nss/build.sh
  build/python313/attrs/build.sh
  build/python313/coverage/build.sh
  build/python313/cryptography/build.sh
  build/python313/jsonrpclib/build.sh
  build/python313/meson/build.sh
  build/python313/meson/patches/compiler_def_static_linker.patch
  build/python313/orjson/build.sh
  build/python313/pip/build.sh
  build/python313/pip/patches/protect-vendor-packages.patch
  build/python313/pycurl/build.sh
  build/python313/pycurl/patches/threading-cleanup.patch
  build/python313/pyopenssl/build.sh
  build/python313/setuptools-rust/build.sh
  build/python313/setuptools/build.sh
  build/python313/typing-extensions/build.sh
  build/xz/build.sh
  build/xz/testsuite.log
  doc/packages.md
Labels: package update

#3906 perl: update to 5.40.2 (r151052)
  build/perl/build.sh
  build/perl/testsuite.log
Labels: package update, backport-PR

#3905 perl: update to 5.40.2 (r151054)
  build/perl/build.sh
  build/perl/testsuite.log
Labels: package update, backport-PR

#3904 perl: update to 5.40.2
  build/perl/build.sh
  build/perl/patches-aarch64/perl-5.40.1.patch
  build/perl/patches-aarch64/series
  build/perl/testsuite.log
  doc/baseline.aarch64
  doc/packages.md
Labels: package update, backport-todo

#3903 perl: update to 5.38.4
  build/perl/build.sh
Labels: package update
